In [2]:
import pymysql
import pandas as pd

connection=pymysql.connect(
    host="s13.hosterpk.com",
    user="pakis104_owaisJaved",
    password="Developers123@",
    database="pakis104_oee_kompass"
)
df = pd.read_sql_query("SELECT dd.id, dd.deviceName, dd.deviceStatus, dd.productCount, dd.machineSpeed, dd.orderId, dd.timestamp, COALESCE(s.id, 0) AS stopId FROM DeviceData dd LEFT JOIN Stops s ON dd.id = s.deviceDataId ORDER BY dd.id ASC;", connection)
connection.close()
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_10628\3055988575.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_10628\3055988575.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT dd.id, dd.deviceName, dd.deviceStatus, dd.productCount, dd.machineSpeed, dd.orderId, dd.timestamp, COALESCE(s.id, 0) AS stopId FROM DeviceData dd LEFT JOIN Stops s ON dd.id = s.deviceDataId ORDER BY dd.id ASC;", connection)

,id,deviceName,deviceStatus,productCount,machineSpeed,orderId,timestamp,stopId
0,343937,MiraFlex 1,0,77052,0,496,02/01/2024 00:00:15,3709
1,343938,MiraFlex 1,0,77052,0,496,02/01/2024 00:00:15,0
2,343939,MiraFlex 1,0,77052,0,496,02/01/2024 00:00:35,0
3,343940,MiraFlex 1,0,77052,0,496,02/01/2024 00:00:35,0
4,343941,MiraFlex 1,0,77052,0,496,02/01/2024 00:00:35,0
...,...,...,...,...,...,...,...,...
215740,559170,MiraFlex 1,0,50386,0,544,04/09/2024 14:45:11,0
215741,559171,MiraFlex 1,0,50386,0,544,04/09/2024 14:45:31,0
215742,559172,MiraFlex 1,0,50386,0,544,04/09/2024 14:45:51,0
215743,559173,MiraFlex 1,0,50386,0,544,04/09/2024 14:46:11,0
215744,559174,MiraFlex 1,0,50386,0,544,04/09/2024 14:46:31,0

In [3]:
df_e=pd.DataFrame(columns=['id', 'deviceName', 'eventName', 'startTime', 'endTime', 'duration', 'totalProduction', 'productionAtStart', 'productionAtEnd','Status', 'speed', 'orderId', 'stopId', 'timestamp'])
df_e["id"]=range(4000)
df_e

,id,deviceName,eventName,startTime,endTime,duration,totalProduction,productionAtStart,productionAtEnd,Status,speed,orderId,stopId,timestamp
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3996,3996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3997,3997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3998,3998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3999,3999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
status=0
j=0
pre_status=1
for i in range(len(df)):
    status=df.iloc[i,2]
    if status==0 and pre_status==1:
        df_e.iloc[j,1]=df.iloc[i,1]
        df_e.iloc[j,2]='Stop'
        df_e.iloc[j,3]=df.iloc[i,6]
        df_e.iloc[j,7]=df.iloc[i,3]
        df_e.iloc[j,9]=df.iloc[i,2]
        df_e.iloc[j,11]=df.iloc[i,5]
        df_e.iloc[j,12]=df.iloc[i,7]
        if (j!=0): 
            df_e.iloc[j-1,4]=df.iloc[i,6]
            df_e.iloc[j-1,8]=df.iloc[i,3]
            df_e.iloc[j-1,13]=df.iloc[i,6]
        j+=1 

    if status==1 and pre_status==0:
        df_e.iloc[j,1]=df.iloc[i,1]
        df_e.iloc[j,2]='Running'
        df_e.iloc[j,3]=df.iloc[i,6]
        df_e.iloc[j,7]=df.iloc[i,3]
        df_e.iloc[j,9]=df.iloc[i,2]
        df_e.iloc[j,11]=df.iloc[i,5]
        df_e.iloc[j,12]=df.iloc[i,7]
        if (j!=0): 
            df_e.iloc[j-1,4]=df.iloc[i,6]
            df_e.iloc[j-1,8]=df.iloc[i,3]
            df_e.iloc[j-1,13]=df.iloc[i,6]
        j+=1  
    pre_status=df.iloc[i,2]     
    df_e

In [5]:
df_e['speed']=pd.to_numeric(df_e['speed'],errors='coerce')
df_e['orderId']=pd.to_numeric(df_e['orderId'],errors='coerce')
df_e['stopId']=pd.to_numeric(df_e['stopId'],errors='coerce')
df_e['timestamp']=pd.to_datetime(df_e['timestamp'],errors='coerce')

In [6]:

df_e.fillna({
    'deviceName': 'Unknown',  # Replace NaN with 'Unknown' or any other suitable default
    'eventName': 'Undefined',
    'startTime': pd.Timestamp(0),  # Example: replace NaT with a default timestamp
    'endTime': pd.Timestamp(0),
    'duration': pd.Timedelta(seconds=0),
    'totalProduction': 0,
    'productionAtStart': 0,
    'productionAtEnd': 0,
    'Status': -1,  # Assuming -1 can be a default for unknown status
    'speed': 0,
    'orderId': 0,
    'stopId': 0,
    'timestamp': pd.Timestamp(0)
}, inplace=True)

df_e

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_10628\1557477025.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_e.fillna({

,id,deviceName,eventName,startTime,endTime,duration,totalProduction,productionAtStart,productionAtEnd,Status,speed,orderId,stopId,timestamp
0,0,MiraFlex 1,Stop,02/01/2024 00:00:15,02/01/2024 00:06:15,0 days,0,77052,77094,0,0.0,496.0,3709.0,2024-02-01 00:06:15
1,1,MiraFlex 1,Running,02/01/2024 00:06:15,02/01/2024 00:08:55,0 days,0,77094,1632062571,1,0.0,496.0,0.0,2024-02-01 00:08:55
2,2,MiraFlex 1,Stop,02/01/2024 00:08:55,02/01/2024 00:19:16,0 days,0,1632062571,78064,0,0.0,496.0,3710.0,2024-02-01 00:19:16
3,3,MiraFlex 1,Running,02/01/2024 00:19:16,02/01/2024 00:20:35,0 days,0,78064,78474,1,0.0,496.0,0.0,2024-02-01 00:20:35
4,4,MiraFlex 1,Stop,02/01/2024 00:20:35,02/01/2024 00:28:35,0 days,0,78474,78494,0,0.0,496.0,3711.0,2024-02-01 00:28:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3995,Unknown,Undefined,1970-01-01 00:00:00,1970-01-01 00:00:00,0 days,0,0,0,-1,0.0,0.0,0.0,1970-01-01 00:00:00
3996,3996,Unknown,Undefined,1970-01-01 00:00:00,1970-01-01 00:00:00,0 days,0,0,0,-1,0.0,0.0,0.0,1970-01-01 00:00:00
3997,3997,Unknown,Undefined,1970-01-01 00:00:00,1970-01-01 00:00:00,0 days,0,0,0,-1,0.0,0.0,0.0,1970-01-01 00:00:00
3998,3998,Unknown,Undefined,1970-01-01 00:00:00,1970-01-01 00:00:00,0 days,0,0,0,-1,0.0,0.0,0.0,1970-01-01 00:00:00
3999,3999,Unknown,Undefined,1970-01-01 00:00:00,1970-01-01 00:00:00,0 days,0,0,0,-1,0.0,0.0,0.0,1970-01-01 00:00:00

In [7]:
df_e.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 4000 non-null   int64
 1   deviceName         4000 non-null   object
 2   eventName          4000 non-null   object
 3   startTime          4000 non-null   object
 4   endTime            4000 non-null   object
 5   duration           4000 non-null   timedelta64[ns]
 6   totalProduction    4000 non-null   int64
 7   productionAtStart  4000 non-null   int64
 8   productionAtEnd    4000 non-null   int64
 9   Status             4000 non-null   int64
 10  speed              4000 non-null   float64
 11  orderId            4000 non-null   float64
 12  stopId             4000 non-null   float64
 13  timestamp          4000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(5), object(4), timedelta64[ns](1)
memory usage: 437.6+ KB

In [8]:
# Establish database connection
connection = pymysql.connect(
    host="s13.hosterpk.com",
    user="pakis104_owaisJaved",
    password="Developers123@",
    database="pakis104_oee_kompass"
)
cursor = connection.cursor()

# Prepare SQL query with placeholders
query = '''
    INSERT INTO events (deviceName, eventName, startTime, endTime, duration, totalProduction, productionAtStart, productionAtEnd, Status, speed, orderId, stopId, timestamp)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
'''

# Loop through DataFrame rows and prepare data for insertion
data_tuples = [
    tuple(row[1:]) for index, row in df_e.iterrows()
]

print(data_tuples)
#Execute the query using executemany for batch insertion
cursor.executemany(query, data_tuples)
connection.commit()

# Clean up
cursor.close()
connection.close()

[('MiraFlex 1', 'Stop', '02/01/2024 00:00:15', '02/01/2024 00:06:15', Timedelta('0 days 00:00:00'), 0, 77052, 77094, 0, 0.0, 496.0, 3709.0, Timestamp('2024-02-01 00:06:15')), ('MiraFlex 1', 'Running', '02/01/2024 00:06:15', '02/01/2024 00:08:55', Timedelta('0 days 00:00:00'), 0, 77094, 1632062571, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 00:08:55')), ('MiraFlex 1', 'Stop', '02/01/2024 00:08:55', '02/01/2024 00:19:16', Timedelta('0 days 00:00:00'), 0, 1632062571, 78064, 0, 0.0, 496.0, 3710.0, Timestamp('2024-02-01 00:19:16')), ('MiraFlex 1', 'Running', '02/01/2024 00:19:16', '02/01/2024 00:20:35', Timedelta('0 days 00:00:00'), 0, 78064, 78474, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 00:20:35')), ('MiraFlex 1', 'Stop', '02/01/2024 00:20:35', '02/01/2024 00:28:35', Timedelta('0 days 00:00:00'), 0, 78474, 78494, 0, 0.0, 496.0, 3711.0, Timestamp('2024-02-01 00:28:35')), ('MiraFlex 1', 'Running', '02/01/2024 00:28:35', '02/01/2024 00:30:15', Timedelta('0 days 00:00:00'), 0, 78494, 78807, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 00:30:15')), ('MiraFlex 1', 'Stop', '02/01/2024 00:30:15', '02/01/2024 01:31:35', Timedelta('0 days 00:00:00'), 0, 78807, 78826, 0, 0.0, 496.0, 3712.0, Timestamp('2024-02-01 01:31:35')), ('MiraFlex 1', 'Running', '02/01/2024 01:31:35', '02/01/2024 01:32:55', Timedelta('0 days 00:00:00'), 0, 78826, 78904, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 01:32:55')), ('MiraFlex 1', 'Stop', '02/01/2024 01:32:55', '02/01/2024 01:36:15', Timedelta('0 days 00:00:00'), 0, 78904, 78911, 0, 0.0, 496.0, 3713.0, Timestamp('2024-02-01 01:36:15')), ('MiraFlex 1', 'Running', '02/01/2024 01:36:15', '02/01/2024 01:36:55', Timedelta('0 days 00:00:00'), 0, 78911, 78948, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 01:36:55')), ('MiraFlex 1', 'Stop', '02/01/2024 01:36:55', '02/01/2024 01:37:55', Timedelta('0 days 00:00:00'), 0, 78948, 78972, 0, 0.0, 496.0, 3714.0, Timestamp('2024-02-01 01:37:55')), ('MiraFlex 1', 'Running', '02/01/2024 01:37:55', '02/01/2024 01:39:35', Timedelta('0 days 00:00:00'), 0, 78972, 79257, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 01:39:35')), ('MiraFlex 1', 'Stop', '02/01/2024 01:39:35', '02/01/2024 01:49:15', Timedelta('0 days 00:00:00'), 0, 79257, 79310, 0, 0.0, 496.0, 3715.0, Timestamp('2024-02-01 01:49:15')), ('MiraFlex 1', 'Running', '02/01/2024 01:49:15', '02/01/2024 01:52:15', Timedelta('0 days 00:00:00'), 0, 79310, 80449, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 01:52:15')), ('MiraFlex 1', 'Stop', '02/01/2024 01:52:15', '02/01/2024 01:54:15', Timedelta('0 days 00:00:00'), 0, 80449, 80467, 0, 0.0, 496.0, 3716.0, Timestamp('2024-02-01 01:54:15')), ('MiraFlex 1', 'Running', '02/01/2024 01:54:15', '02/01/2024 02:08:15', Timedelta('0 days 00:00:00'), 0, 80467, 86023, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 02:08:15')), ('MiraFlex 1', 'Stop', '02/01/2024 02:08:15', '02/01/2024 02:13:55', Timedelta('0 days 00:00:00'), 0, 86023, 86032, 0, 0.0, 496.0, 3717.0, Timestamp('2024-02-01 02:13:55')), ('MiraFlex 1', 'Running', '02/01/2024 02:13:55', '02/01/2024 02:31:35', Timedelta('0 days 00:00:00'), 0, 86032, 92994, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 02:31:35')), ('MiraFlex 1', 'Stop', '02/01/2024 02:31:35', '02/01/2024 03:17:15', Timedelta('0 days 00:00:00'), 0, 92994, 93012, 0, 0.0, 496.0, 3718.0, Timestamp('2024-02-01 03:17:15')), ('MiraFlex 1', 'Running', '02/01/2024 03:17:15', '02/01/2024 03:17:35', Timedelta('0 days 00:00:00'), 0, 93012, 93024, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 03:17:35')), ('MiraFlex 1', 'Stop', '02/01/2024 03:17:35', '02/01/2024 03:21:15', Timedelta('0 days 00:00:00'), 0, 93024, 93054, 0, 0.0, 496.0, 3719.0, Timestamp('2024-02-01 03:21:15')), ('MiraFlex 1', 'Running', '02/01/2024 03:21:15', '02/01/2024 03:23:15', Timedelta('0 days 00:00:00'), 0, 93054, 93349, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 03:23:15')), ('MiraFlex 1', 'Stop', '02/01/2024 03:23:15', '02/01/2024 03:36:15', Timedelta('0 days 00:00:00'), 0, 93349, 93383, 0, 0.0, 496.0, 3720.0, Timestamp('2024-02-01 03:36:15')), ('MiraFlex 1', 'Running', '02/01/2024 03:36:15', '02/01/2024 03:36:55', Timedelta('0 days 00:00:00'), 0, 93383, 93505, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 03:36:55')), ('MiraFlex 1', 'Stop', '02/01/2024 03:36:55', '02/01/2024 03:44:55', Timedelta('0 days 00:00:00'), 0, 93505, 93610, 0, 0.0, 496.0, 3721.0, Timestamp('2024-02-01 03:44:55')), ('MiraFlex 1', 'Running', '02/01/2024 03:44:55', '02/01/2024 03:51:55', Timedelta('0 days 00:00:00'), 0, 93610, 96286, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 03:51:55')), ('MiraFlex 1', 'Stop', '02/01/2024 03:51:55', '02/01/2024 04:10:17', Timedelta('0 days 00:00:00'), 0, 96286, 96302, 0, 0.0, 496.0, 3722.0, Timestamp('2024-02-01 04:10:17')), ('MiraFlex 1', 'Running', '02/01/2024 04:10:17', '02/01/2024 04:12:36', Timedelta('0 days 00:00:00'), 0, 96302, 96783, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 04:12:36')), ('MiraFlex 1', 'Stop', '02/01/2024 04:12:36', '02/01/2024 04:19:56', Timedelta('0 days 00:00:00'), 0, 96783, 96861, 0, 0.0, 496.0, 3723.0, Timestamp('2024-02-01 04:19:56')), ('MiraFlex 1', 'Running', '02/01/2024 04:19:56', '02/01/2024 04:24:36', Timedelta('0 days 00:00:00'), 0, 96861, 98667, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 04:24:36')), ('MiraFlex 1', 'Stop', '02/01/2024 04:24:36', '02/01/2024 04:42:55', Timedelta('0 days 00:00:00'), 0, 98667, 98683, 0, 0.0, 496.0, 3724.0, Timestamp('2024-02-01 04:42:55')), ('MiraFlex 1', 'Running', '02/01/2024 04:42:55', '02/01/2024 04:50:56', Timedelta('0 days 00:00:00'), 0, 98683, 101857, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 04:50:56')), ('MiraFlex 1', 'Stop', '02/01/2024 04:50:56', '02/01/2024 04:54:55', Timedelta('0 days 00:00:00'), 0, 101857, 101869, 0, 0.0, 496.0, 3725.0, Timestamp('2024-02-01 04:54:55')), ('MiraFlex 1', 'Running', '02/01/2024 04:54:55', '02/01/2024 05:03:56', Timedelta('0 days 00:00:00'), 0, 101869, 105385, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 05:03:56')), ('MiraFlex 1', 'Stop', '02/01/2024 05:03:56', '02/01/2024 05:05:55', Timedelta('0 days 00:00:00'), 0, 105385, 105427, 0, 0.0, 496.0, 3726.0, Timestamp('2024-02-01 05:05:55')), ('MiraFlex 1', 'Running', '02/01/2024 05:05:55', '02/01/2024 05:11:35', Timedelta('0 days 00:00:00'), 0, 105427, 107569, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 05:11:35')), ('MiraFlex 1', 'Stop', '02/01/2024 05:11:35', '02/01/2024 06:11:40', Timedelta('0 days 00:00:00'), 0, 107569, 107595, 0, 0.0, 496.0, 3727.0, Timestamp('2024-02-01 06:11:40')), ('MiraFlex 1', 'Running', '02/01/2024 06:11:40', '02/01/2024 06:12:00', Timedelta('0 days 00:00:00'), 0, 107595, 107600, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 06:12:00')), ('MiraFlex 1', 'Stop', '02/01/2024 06:12:00', '02/01/2024 06:16:00', Timedelta('0 days 00:00:00'), 0, 107600, 107633, 0, 0.0, 496.0, 3728.0, Timestamp('2024-02-01 06:16:00')), ('MiraFlex 1', 'Running', '02/01/2024 06:16:00', '02/01/2024 06:18:00', Timedelta('0 days 00:00:00'), 0, 107633, 107934, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 06:18:00')), ('MiraFlex 1', 'Stop', '02/01/2024 06:18:00', '02/01/2024 06:28:47', Timedelta('0 days 00:00:00'), 0, 107934, 107941, 0, 0.0, 496.0, 3729.0, Timestamp('2024-02-01 06:28:47')), ('MiraFlex 1', 'Running', '02/01/2024 06:28:47', '02/01/2024 06:31:16', Timedelta('0 days 00:00:00'), 0, 107941, 108181, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 06:31:16')), ('MiraFlex 1', 'Stop', '02/01/2024 06:31:16', '02/01/2024 06:50:18', Timedelta('0 days 00:00:00'), 0, 108181, 108194, 0, 0.0, 496.0, 3730.0, Timestamp('2024-02-01 06:50:18')), ('MiraFlex 1', 'Running', '02/01/2024 06:50:18', '02/01/2024 06:51:40', Timedelta('0 days 00:00:00'), 0, 108194, 108406, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 06:51:40')), ('MiraFlex 1', 'Stop', '02/01/2024 06:51:40', '02/01/2024 07:48:57', Timedelta('0 days 00:00:00'), 0, 108406, 108413, 0, 0.0, 496.0, 0.0, Timestamp('2024-02-01 07:48:57')), ('MiraFlex 1', 'Running', '02/01/2024 07:48:57', '02/01/2024 07:49:36', Timedelta('0 days 00:00:00'), 0, 108413, 108562, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 07:49:36')), ('MiraFlex 1', 'Stop', '02/01/2024 07:49:36', '02/01/2024 07:56:16', Timedelta('0 days 00:00:00'), 0, 108562, 108574, 0, 0.0, 496.0, 3696.0, Timestamp('2024-02-01 07:56:16')), ('MiraFlex 1', 'Running', '02/01/2024 07:56:16', '02/01/2024 07:59:16', Timedelta('0 days 00:00:00'), 0, 108574, 108958, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 07:59:16')), ('MiraFlex 1', 'Stop', '02/01/2024 07:59:16', '02/01/2024 08:16:26', Timedelta('0 days 00:00:00'), 0, 108958, 109059, 0, 0.0, 496.0, 3697.0, Timestamp('2024-02-01 08:16:26')), ('MiraFlex 1', 'Running', '02/01/2024 08:16:26', '02/01/2024 08:17:06', Timedelta('0 days 00:00:00'), 0, 109059, 109267, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 08:17:06')), ('MiraFlex 1', 'Stop', '02/01/2024 08:17:06', '02/01/2024 08:37:08', Timedelta('0 days 00:00:00'), 0, 109267, 109304, 0, 0.0, 496.0, 3698.0, Timestamp('2024-02-01 08:37:08')), ('MiraFlex 1', 'Running', '02/01/2024 08:37:08', '02/01/2024 08:39:08', Timedelta('0 days 00:00:00'), 0, 109304, 109521, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 08:39:08')), ('MiraFlex 1', 'Stop', '02/01/2024 08:39:08', '02/01/2024 09:41:11', Timedelta('0 days 00:00:00'), 0, 109521, 109528, 0, 0.0, 496.0, 3699.0, Timestamp('2024-02-01 09:41:11')), ('MiraFlex 1', 'Running', '02/01/2024 09:41:11', '02/01/2024 09:43:32', Timedelta('0 days 00:00:00'), 0, 109528, 109901, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 09:43:32')), ('MiraFlex 1', 'Stop', '02/01/2024 09:43:32', '02/01/2024 10:14:38', Timedelta('0 days 00:00:00'), 0, 109901, 109929, 0, 0.0, 496.0, 3700.0, Timestamp('2024-02-01 10:14:38')), ('MiraFlex 1', 'Running', '02/01/2024 10:14:38', '02/01/2024 10:18:59', Timedelta('0 days 00:00:00'), 0, 109929, 110449, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 10:18:59')), ('MiraFlex 1', 'Stop', '02/01/2024 10:18:59', '02/01/2024 10:26:49', Timedelta('0 days 00:00:00'), 0, 110449, 110515, 0, 0.0, 496.0, 3701.0, Timestamp('2024-02-01 10:26:49')), ('MiraFlex 1', 'Running', '02/01/2024 10:26:49', '02/01/2024 10:53:07', Timedelta('0 days 00:00:00'), 0, 110515, 120995, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 10:53:07')), ('MiraFlex 1', 'Stop', '02/01/2024 10:53:07', '02/01/2024 10:59:28', Timedelta('0 days 00:00:00'), 0, 120995, 120997, 0, 0.0, 496.0, 3702.0, Timestamp('2024-02-01 10:59:28')), ('MiraFlex 1', 'Running', '02/01/2024 10:59:28', '02/01/2024 11:36:08', Timedelta('0 days 00:00:00'), 0, 120997, 135646, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 11:36:08')), ('MiraFlex 1', 'Stop', '02/01/2024 11:36:08', '02/01/2024 12:51:49', Timedelta('0 days 00:00:00'), 0, 135646, 135669, 0, 0.0, 496.0, 3703.0, Timestamp('2024-02-01 12:51:49')), ('MiraFlex 1', 'Running', '02/01/2024 12:51:49', '02/01/2024 12:53:09', Timedelta('0 days 00:00:00'), 0, 135669, 135839, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 12:53:09')), ('MiraFlex 1', 'Stop', '02/01/2024 12:53:09', '02/01/2024 12:55:28', Timedelta('0 days 00:00:00'), 0, 135839, 135855, 0, 0.0, 496.0, 3704.0, Timestamp('2024-02-01 12:55:28')), ('MiraFlex 1', 'Running', '02/01/2024 12:55:28', '02/01/2024 12:57:49', Timedelta('0 days 00:00:00'), 0, 135855, 136255, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 12:57:49')), ('MiraFlex 1', 'Stop', '02/01/2024 12:57:49', '02/01/2024 13:05:48', Timedelta('0 days 00:00:00'), 0, 136255, 136294, 0, 0.0, 496.0, 3705.0, Timestamp('2024-02-01 13:05:48')), ('MiraFlex 1', 'Running', '02/01/2024 13:05:48', '02/01/2024 13:06:49', Timedelta('0 days 00:00:00'), 0, 136294, 136515, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 13:06:49')), ('MiraFlex 1', 'Stop', '02/01/2024 13:06:49', '02/01/2024 13:13:48', Timedelta('0 days 00:00:00'), 0, 136515, 136547, 0, 0.0, 496.0, 3706.0, Timestamp('2024-02-01 13:13:48')), ('MiraFlex 1', 'Running', '02/01/2024 13:13:48', '02/01/2024 13:26:31', Timedelta('0 days 00:00:00'), 0, 136547, 1632062571, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 13:26:31')), ('MiraFlex 1', 'Stop', '02/01/2024 13:26:31', '02/01/2024 13:26:50', Timedelta('0 days 00:00:00'), 0, 1632062571, 141747, 0, 0.0, 496.0, 3707.0, Timestamp('2024-02-01 13:26:50')), ('MiraFlex 1', 'Running', '02/01/2024 13:26:50', '02/01/2024 13:39:49', Timedelta('0 days 00:00:00'), 0, 141747, 1632062571, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 13:39:49')), ('MiraFlex 1', 'Stop', '02/01/2024 13:39:49', '02/01/2024 13:40:09', Timedelta('0 days 00:00:00'), 0, 1632062571, 147097, 0, 0.0, 496.0, 3708.0, Timestamp('2024-02-01 13:40:09')), ('MiraFlex 1', 'Running', '02/01/2024 13:40:09', '02/01/2024 13:56:49', Timedelta('0 days 00:00:00'), 0, 147097, 153709, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 13:56:49')), ('MiraFlex 1', 'Stop', '02/01/2024 13:56:49', '02/01/2024 15:33:10', Timedelta('0 days 00:00:00'), 0, 153709, 153714, 0, 0.0, 496.0, 0.0, Timestamp('2024-02-01 15:33:10')), ('MiraFlex 1', 'Running', '02/01/2024 15:33:10', '02/01/2024 15:40:31', Timedelta('0 days 00:00:00'), 0, 153714, 154428, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 15:40:31')), ('MiraFlex 1', 'Stop', '02/01/2024 15:40:31', '02/01/2024 15:46:10', Timedelta('0 days 00:00:00'), 0, 154428, 154488, 0, 0.0, 496.0, 3637.0, Timestamp('2024-02-01 15:46:10')), ('MiraFlex 1', 'Running', '02/01/2024 15:46:10', '02/01/2024 15:46:50', Timedelta('0 days 00:00:00'), 0, 154488, 154630, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 15:46:50')), ('MiraFlex 1', 'Stop', '02/01/2024 15:46:50', '02/01/2024 16:07:11', Timedelta('0 days 00:00:00'), 0, 154630, 154665, 0, 0.0, 496.0, 3638.0, Timestamp('2024-02-01 16:07:11')), ('MiraFlex 1', 'Running', '02/01/2024 16:07:11', '02/01/2024 16:07:51', Timedelta('0 days 00:00:00'), 0, 154665, 154807, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 16:07:51')), ('MiraFlex 1', 'Stop', '02/01/2024 16:07:51', '02/01/2024 16:09:30', Timedelta('0 days 00:00:00'), 0, 154807, 154833, 0, 0.0, 496.0, 3639.0, Timestamp('2024-02-01 16:09:30')), ('MiraFlex 1', 'Running', '02/01/2024 16:09:30', '02/01/2024 16:10:30', Timedelta('0 days 00:00:00'), 0, 154833, 155112, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 16:10:30')), ('MiraFlex 1', 'Stop', '02/01/2024 16:10:30', '02/01/2024 16:47:01', Timedelta('0 days 00:00:00'), 0, 155112, 155138, 0, 0.0, 496.0, 3640.0, Timestamp('2024-02-01 16:47:01')), ('MiraFlex 1', 'Running', '02/01/2024 16:47:01', '02/01/2024 16:53:00', Timedelta('0 days 00:00:00'), 0, 155138, 155699, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 16:53:00')), ('MiraFlex 1', 'Stop', '02/01/2024 16:53:00', '02/01/2024 17:02:40', Timedelta('0 days 00:00:00'), 0, 155699, 155751, 0, 0.0, 496.0, 3641.0, Timestamp('2024-02-01 17:02:40')), ('MiraFlex 1', 'Running', '02/01/2024 17:02:40', '02/01/2024 17:03:40', Timedelta('0 days 00:00:00'), 0, 155751, 156087, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 17:03:40')), ('MiraFlex 1', 'Stop', '02/01/2024 17:03:40', '02/01/2024 17:09:01', Timedelta('0 days 00:00:00'), 0, 156087, 156133, 0, 0.0, 496.0, 3642.0, Timestamp('2024-02-01 17:09:01')), ('MiraFlex 1', 'Running', '02/01/2024 17:09:01', '02/01/2024 17:09:41', Timedelta('0 days 00:00:00'), 0, 156133, 156281, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 17:09:41')), ('MiraFlex 1', 'Stop', '02/01/2024 17:09:41', '02/01/2024 17:43:01', Timedelta('0 days 00:00:00'), 0, 156281, 156285, 0, 0.0, 496.0, 3643.0, Timestamp('2024-02-01 17:43:01')), ('MiraFlex 1', 'Running', '02/01/2024 17:43:01', '02/01/2024 17:45:41', Timedelta('0 days 00:00:00'), 0, 156285, 157237, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 17:45:41')), ('MiraFlex 1', 'Stop', '02/01/2024 17:45:41', '02/01/2024 17:46:41', Timedelta('0 days 00:00:00'), 0, 157237, 157286, 0, 0.0, 496.0, 3644.0, Timestamp('2024-02-01 17:46:41')), ('MiraFlex 1', 'Running', '02/01/2024 17:46:41', '02/01/2024 18:01:01', Timedelta('0 days 00:00:00'), 0, 157286, 162083, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 18:01:01')), ('MiraFlex 1', 'Stop', '02/01/2024 18:01:01', '02/01/2024 18:10:41', Timedelta('0 days 00:00:00'), 0, 162083, 162174, 0, 0.0, 496.0, 3645.0, Timestamp('2024-02-01 18:10:41')), ('MiraFlex 1', 'Running', '02/01/2024 18:10:41', '02/01/2024 18:11:01', Timedelta('0 days 00:00:00'), 0, 162174, 162227, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 18:11:01')), ('MiraFlex 1', 'Stop', '02/01/2024 18:11:01', '02/01/2024 18:12:01', Timedelta('0 days 00:00:00'), 0, 162227, 162233, 0, 0.0, 496.0, 3646.0, Timestamp('2024-02-01 18:12:01')), ('MiraFlex 1', 'Running', '02/01/2024 18:12:01', '02/01/2024 18:24:21', Timedelta('0 days 00:00:00'), 0, 162233, 1632062571, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 18:24:21')), ('MiraFlex 1', 'Stop', '02/01/2024 18:24:21', '02/01/2024 18:24:41', Timedelta('0 days 00:00:00'), 0, 1632062571, 166723, 0, 0.0, 496.0, 3647.0, Timestamp('2024-02-01 18:24:41')), ('MiraFlex 1', 'Running', '02/01/2024 18:24:41', '02/01/2024 18:28:41', Timedelta('0 days 00:00:00'), 0, 166723, 168068, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 18:28:41')), ('MiraFlex 1', 'Stop', '02/01/2024 18:28:41', '02/01/2024 18:53:01', Timedelta('0 days 00:00:00'), 0, 168068, 168152, 0, 0.0, 496.0, 3648.0, Timestamp('2024-02-01 18:53:01')), ('MiraFlex 1', 'Running', '02/01/2024 18:53:01', '02/01/2024 18:54:01', Timedelta('0 days 00:00:00'), 0, 168152, 168397, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 18:54:01')), ('MiraFlex 1', 'Stop', '02/01/2024 18:54:01', '02/01/2024 18:59:41', Timedelta('0 days 00:00:00'), 0, 168397, 168407, 0, 0.0, 496.0, 3649.0, Timestamp('2024-02-01 18:59:41')), ('MiraFlex 1', 'Running', '02/01/2024 18:59:41', '02/01/2024 19:21:22', Timedelta('0 days 00:00:00'), 0, 168407, 175944, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 19:21:22')), ('MiraFlex 1', 'Stop', '02/01/2024 19:21:22', '02/01/2024 19:37:02', Timedelta('0 days 00:00:00'), 0, 175944, 175971, 0, 0.0, 496.0, 3650.0, Timestamp('2024-02-01 19:37:02')), ('MiraFlex 1', 'Running', '02/01/2024 19:37:02', '02/01/2024 19:37:42', Timedelta('0 days 00:00:00'), 0, 175971, 176098, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 19:37:42')), ('MiraFlex 1', 'Stop', '02/01/2024 19:37:42', '02/01/2024 19:39:42', Timedelta('0 days 00:00:00'), 0, 176098, 176151, 0, 0.0, 496.0, 3651.0, Timestamp('2024-02-01 19:39:42')), ('MiraFlex 1', 'Running', '02/01/2024 19:39:42', '02/01/2024 19:40:02', Timedelta('0 days 00:00:00'), 0, 176151, 176215, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 19:40:02')), ('MiraFlex 1', 'Stop', '02/01/2024 19:40:02', '02/01/2024 19:45:42', Timedelta('0 days 00:00:00'), 0, 176215, 176217, 0, 0.0, 496.0, 3652.0, Timestamp('2024-02-01 19:45:42')), ('MiraFlex 1', 'Running', '02/01/2024 19:45:42', '02/01/2024 19:46:42', Timedelta('0 days 00:00:00'), 0, 176217, 176440, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 19:46:42')), ('MiraFlex 1', 'Stop', '02/01/2024 19:46:42', '02/01/2024 19:56:42', Timedelta('0 days 00:00:00'), 0, 176440, 176478, 0, 0.0, 496.0, 3653.0, Timestamp('2024-02-01 19:56:42')), ('MiraFlex 1', 'Running', '02/01/2024 19:56:42', '02/01/2024 19:57:22', Timedelta('0 days 00:00:00'), 0, 176478, 176624, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 19:57:22')), ('MiraFlex 1', 'Stop', '02/01/2024 19:57:22', '02/01/2024 20:16:23', Timedelta('0 days 00:00:00'), 0, 176624, 176629, 0, 0.0, 496.0, 3654.0, Timestamp('2024-02-01 20:16:23')), ('MiraFlex 1', 'Running', '02/01/2024 20:16:23', '02/01/2024 20:18:42', Timedelta('0 days 00:00:00'), 0, 176629, 177305, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 20:18:42')), ('MiraFlex 1', 'Stop', '02/01/2024 20:18:42', '02/01/2024 21:06:42', Timedelta('0 days 00:00:00'), 0, 177305, 177342, 0, 0.0, 496.0, 3655.0, Timestamp('2024-02-01 21:06:42')), ('MiraFlex 1', 'Running', '02/01/2024 21:06:42', '02/01/2024 21:15:43', Timedelta('0 days 00:00:00'), 0, 177342, 180354, 1, 0.0, 496.0, 0.0, Timestamp('2024-02-01 21:15:43')), ('MiraFlex 1', 'Stop', '02/01/2024 21:15:43', '02/01/2024 21:27:23', Timedelta('0 days 00:00:00'), 0, 180354, 180391, 0, 0.0, 496.0, 3656.0, Timestamp('2024-02-01 21:27:23')), ('MiraFlex 1', 'Running', '02/01/2024 21:27:23', '02/01/2024 21:51:03', Timedelta('0 days 00:00:00'), 0, 180391, 188697, 1, 0.0, 496.0, 0.0, Times