In [2]:
import pymysql
import pandas as pd

connection=pymysql.connect(
    host="s13.hosterpk.com",
    user="pakis104_owaisJaved",
    password="Developers123@",
    database="pakis104_oee_kompass"
)
df_c = pd.read_sql_query("SELECT * FROM CompleteOrders", connection)
df_d = pd.read_sql_query("SELECT * FROM DeviceData", connection)
print(df_c)
print(df_d)
connection.close()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14468\2268542669.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14468\2268542669.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_c = pd.read_sql_query("SELECT * FROM CompleteOrders", connection)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14468\2268542669.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_d = pd.read_sql_query("SELECT * FROM DeviceData", connection)

      id  deviceName  productCount  deviceStatus poNumber     skuName  \
0    416  MiraFlex 1        108406             0   619815   PET (400)
1    417  MiraFlex 1        153709             0   619815   PET (400)
2    418  MiraFlex 1        189824             0   619815   PET (400)
3    419  MiraFlex 1        189824             0   619815   PET (400)
4    420  MiraFlex 1        193779             0   619815   PET (400)
..   ...         ...           ...           ...      ...         ...
196  618  MiraFlex 1             0             0   118289  LDPE (400)
197  619  MiraFlex 1         72600             1   118289  LDPE (400)
198  620  MiraFlex 1        106758             0   118289  LDPE (400)
199  621  MiraFlex 1         97482             0   118289  LDPE (400)
200  622  MiraFlex 1         50386             0   118289  LDPE (400)

     skuTarget shiftName teamName distributerName  ... orderCompletionStatus  \
0          400         C                           ...                     1
1          400         A                           ...                     1
2          400         B                           ...                     1
3          400         C                           ...                     1
4          400         A                           ...                     1
..         ...       ...      ...             ...  ...                   ...
196        400         A                           ...                     1
197        400         A                           ...                     1
198        400         B                           ...                     1
199        400         C                           ...                     1
200        400         A                           ...                     1

    shippableProduct  scrap  upTime  downTime  orderId  shiftStartTime  \
0                  0      0      99     19294      496        23:00:00
1                  0      0     187     17607      496        07:00:00
2                  0      0     865     20089      496        15:00:00
3                  0      0     360         0      496        23:00:00
4                  0      0      28     26774      496        07:00:00
..               ...    ...     ...       ...      ...             ...
196                0      0      20      2600      544        07:00:00
197                0      0   11682     15102      544        07:00:00
198                0      0   16243     12521      544        15:00:00
199                0      0   15041     13743      544        23:00:00
200                0      0    6962     21022      544        07:00:00

     shiftEndTime             qtyInKg            timestamp
0        07:00:00  1121.8299033903825  02/01/2024 06:59:56
1        15:00:00  1590.6517581503056  02/01/2024 14:59:50
2        23:00:00   1964.380087563773  02/01/2024 22:59:43
3        07:00:00   1964.380087563773  02/02/2024 06:59:59
4        15:00:00   2005.312537540254  02/02/2024 14:53:41
..            ...                 ...                  ...
196      15:00:00                   0  04/07/2024 07:43:46
197      15:00:00  4748.2690575704255  04/08/2024 14:59:59
198      23:00:00   6982.327854742513  04/08/2024 22:59:43
199      07:00:00    6375.66715016273  04/09/2024 06:59:47
200      15:00:00    3295.38708541352  04/09/2024 14:46:31

[201 rows x 22 columns]
            id  deviceName  deviceStatus  productCount poNumber poStart poEnd  \
0       343937  MiraFlex 1             0         77052   619815
1       343938  MiraFlex 1             0         77052   619815
2       343939  MiraFlex 1             0         77052   619815
3       343940  MiraFlex 1             0         77052   619815
4       343941  MiraFlex 1             0         77052   619815
...        ...         ...           ...           ...      ...     ...   ...
215233  559170  MiraFlex 1             0         50386   118289
215234  559171  MiraFlex 1             0         50386   118289
215235  559172  MiraFlex 1             0         50386   118289
215236  559173  MiraFlex 1             0         50386   118289
215237  559174  MiraFlex 1             0         50386   118289

           skuName  skuTarget teamName distributerName  orderId  \
0        PET (400)        400                               496
1        PET (400)        400                               496
2        PET (400)        400                               496
3        PET (400)        400                               496
4        PET (400)        400                               496
...            ...        ...      ...             ...      ...
215233  LDPE (400)        400                               544
215234  LDPE (400)        400                               544
215235  LDPE (400)        400                               544
215236  LDPE (400)        400                               544
215237  LDPE (400)        400                               544

                  timestamp  scrap causeOne  machineSpeed            qtyInKg  \
0       02/01/2024 00:00:15      0                      0  797.3707319897238
1       02/01/2024 00:00:15      0                      0  797.3707319897238
2       02/01/2024 00:00:35      0                      0  797.3707319897238
3       02/01/2024 00:00:35      0                      0  797.3707319897238
4       02/01/2024 00:00:35      0                      0  797.3707319897238
...                     ...    ...      ...           ...                ...
215233  04/09/2024 14:45:11      0                      0   3295.38708541352
215234  04/09/2024 14:45:31      0                      0   3295.38708541352
215235  04/09/2024 14:45:51      0                      0   3295.38708541352
215236  04/09/2024 14:46:11      0                      0   3295.38708541352
215237  04/09/2024 14:46:31      0                      0   3295.38708541352

        stopId  completeOrderId
0            0                0
1            0                0
2            0                0
3            0                0
4            0                0
...        ...              ...
215233       0                0
215234       0                0
215235       0                0
215236       0                0
215237       0                0

[215238 rows x 19 columns]

In [30]:

df_stops=pd.DataFrame(columns=["id","startTime","endTime","downtime","orderStart","orderEnd","stopUpdatedTime","stopUpdatedBy","categoryName","causeOne","causeTwo","causeThree","causeFour","causeFive","childDeviceName","deviceName","shiftName","shiftStartTime","shiftEndTime","deviceDataId","orderId","mainStopId","skuName","comment","reasonOne","reasonTwo","Status"])

df_stops["id"]=range(3000)

In [31]:
df_stops['categoryName']="Unplanned"
df_stops['childDeviceName']="MiraFlex 1"
df_stops['deviceName']="MiraFlex 1"
j=0
for i in range(98,102):

    
    print(df_c.iloc[i,17])
    df_stops.iloc[j,20]=df_c.iloc[i,17]
    df_stops.iloc[j,4]=df_c.iloc[i,10]
    df_stops.iloc[j,5]=df_c.iloc[i,11]
    df_stops.iloc[j,3]=df_c.iloc[i,16]
    df_stops.iloc[j,16]=df_c.iloc[i,7]
    df_stops.iloc[j,17]=df_c.iloc[i,18]
    df_stops.iloc[j,18]=df_c.iloc[i,19]
    df_stops.iloc[j,22]=df_c.iloc[i,5]
    df_combine = pd.merge(df_stops, df_d, left_on="orderId", right_on="orderId", how="inner", suffixes=("_stops", "_d"))
    last=1
    #print(df_stops.iloc[0,4],df_stops.iloc[0,5])
    for k in range(len(df_combine)): 
        if ((str(df_stops.iloc[j,4])<=df_combine.iloc[k,38]) and (df_stops.iloc[j,5]>df_combine.iloc[k,38])):
            current=df_combine.iloc[k,29]
            if ((current!=last)and(current==0)):
                df_stops.iloc[j,1]=df_combine.iloc[k,38]
                j+=1
                df_stops.iloc[j,20]=df_c.iloc[i,17]
                df_stops.iloc[j,4]=df_c.iloc[i,10]
                df_stops.iloc[j,5]=df_c.iloc[i,11]
                df_stops.iloc[j,3]=df_c.iloc[i,16]
                df_stops.iloc[j,16]=df_c.iloc[i,7]
                df_stops.iloc[j,17]=df_c.iloc[i,18]
                df_stops.iloc[j,18]=df_c.iloc[i,19]
                df_stops.iloc[j,22]=df_c.iloc[i,5]
                
            if ((current!=last)and(current==1)): 
                df_stops.iloc[j-1,2]=df_combine.iloc[k,38]
                
            last=df_combine.iloc[k,29] 
        if pd.isna(df_stops.iloc[j-1, 2]):  # Check if the value is NaN
            df_stops.iloc[j-1, 2] = df_stops.iloc[j, 5]
            print(j,df_stops.iloc[j-1, 2] ,df_stops.iloc[j, 5])
            
        
#df_combine

536
0 03/02/2024 15:08:53 03/02/2024 15:08:53
536
1 03/02/2024 22:59:57 03/02/2024 22:59:57
2 03/02/2024 22:59:57 03/02/2024 22:59:57
3 03/02/2024 22:59:57 03/02/2024 22:59:57
4 03/02/2024 22:59:57 03/02/2024 22:59:57
5 03/02/2024 22:59:57 03/02/2024 22:59:57
6 03/02/2024 22:59:57 03/02/2024 22:59:57
7 03/02/2024 22:59:57 03/02/2024 22:59:57
8 03/02/2024 22:59:57 03/02/2024 22:59:57
9 03/02/2024 22:59:57 03/02/2024 22:59:57
10 03/02/2024 22:59:57 03/02/2024 22:59:57
11 03/02/2024 22:59:57 03/02/2024 22:59:57
536
12 03/02/2024 23:59:57 03/02/2024 23:59:57
13 03/02/2024 23:59:57 03/02/2024 23:59:57
14 03/02/2024 23:59:57 03/02/2024 23:59:57
15 03/02/2024 23:59:57 03/02/2024 23:59:57
16 03/02/2024 23:59:57 03/02/2024 23:59:57
17 03/02/2024 23:59:57 03/02/2024 23:59:57
18 03/02/2024 23:59:57 03/02/2024 23:59:57
19 03/02/2024 23:59:57 03/02/2024 23:59:57
20 03/02/2024 23:59:57 03/02/2024 23:59:57
21 03/02/2024 23:59:57 03/02/2024 23:59:57
22 03/02/2024 23:59:57 03/02/2024 23:59:57
23 03/02/2024 23:59:57 03/02/2024 23:59:57
24 03/02/2024 23:59:57 03/02/2024 23:59:57
25 03/02/2024 23:59:57 03/02/2024 23:59:57
26 03/02/2024 23:59:57 03/02/2024 23:59:57
27 03/02/2024 23:59:57 03/02/2024 23:59:57
28 03/02/2024 23:59:57 03/02/2024 23:59:57
29 03/02/2024 23:59:57 03/02/2024 23:59:57
30 03/02/2024 23:59:57 03/02/2024 23:59:57
31 03/02/2024 23:59:57 03/02/2024 23:59:57
32 03/02/2024 23:59:57 03/02/2024 23:59:57
33 03/02/2024 23:59:57 03/02/2024 23:59:57
34 03/02/2024 23:59:57 03/02/2024 23:59:57
35 03/02/2024 23:59:57 03/02/2024 23:59:57
36 03/02/2024 23:59:57 03/02/2024 23:59:57
37 03/02/2024 23:59:57 03/02/2024 23:59:57
38 03/02/2024 23:59:57 03/02/2024 23:59:57
39 03/02/2024 23:59:57 03/02/2024 23:59:57
40 03/02/2024 23:59:57 03/02/2024 23:59:57
41 03/02/2024 23:59:57 03/02/2024 23:59:57
42 03/02/2024 23:59:57 03/02/2024 23:59:57
43 03/02/2024 23:59:57 03/02/2024 23:59:57
44 03/02/2024 23:59:57 03/02/2024 23:59:57
45 03/02/2024 23:59:57 03/02/2024 23:59:57
46 03/02/2024 23:59:57 03/02/2024 23:59:57
47 03/02/2024 23:59:57 03/02/2024 23:59:57
48 03/02/2024 23:59:57 03/02/2024 23:59:57
536
49 03/03/2024 06:18:20 03/03/2024 06:18:20
50 03/03/2024 06:18:20 03/03/2024 06:18:20
51 03/03/2024 06:18:20 03/03/2024 06:18:20
52 03/03/2024 06:18:20 03/03/2024 06:18:20
53 03/03/2024 06:18:20 03/03/2024 06:18:20
54 03/03/2024 06:18:20 03/03/2024 06:18:20
55 03/03/2024 06:18:20 03/03/2024 06:18:20
56 03/03/2024 06:18:20 03/03/2024 06:18:20
57 03/03/2024 06:18:20 03/03/2024 06:18:20
58 03/03/2024 06:18:20 03/03/2024 06:18:20
59 03/03/2024 06:18:20 03/03/2024 06:18:20
60 03/03/2024 06:18:20 03/03/2024 06:18:20
61 03/03/2024 06:18:20 03/03/2024 06:18:20
62 03/03/2024 06:18:20 03/03/2024 06:18:20
63 03/03/2024 06:18:20 03/03/2024 06:18:20
64 03/03/2024 06:18:20 03/03/2024 06:18:20
65 03/03/2024 06:18:20 03/03/2024 06:18:20
66 03/03/2024 06:18:20 03/03/2024 06:18:20
67 03/03/2024 06:18:20 03/03/2024 06:18:20
68 03/03/2024 06:18:20 03/03/2024 06:18:20
69 03/03/2024 06:18:20 03/03/2024 06:18:20
70 03/03/2024 06:18:20 03/03/2024 06:18:20
71 03/03/2024 06:18:20 03/03/2024 06:18:20
72 03/03/2024 06:18:20 03/03/2024 06:18:20
73 03/03/2024 06:18:20 03/03/2024 06:18:20
74 03/03/2024 06:18:20 03/03/2024 06:18:20
75 03/03/2024 06:18:20 03/03/2024 06:18:20
76 03/03/2024 06:18:20 03/03/2024 06:18:20
77 03/03/2024 06:18:20 03/03/2024 06:18:20
78 03/03/2024 06:18:20 03/03/2024 06:18:20
79 03/03/2024 06:18:20 03/03/2024 06:18:20
80 03/03/2024 06:18:20 03/03/2024 06:18:20
81 03/03/2024 06:18:20 03/03/2024 06:18:20
82 03/03/2024 06:18:20 03/03/2024 06:18:20
83 03/03/2024 06:18:20 03/03/2024 06:18:20
84 03/03/2024 06:18:20 03/03/2024 06:18:20
85 03/03/2024 06:18:20 03/03/2024 06:18:20
86 03/03/2024 06:18:20 03/03/2024 06:18:20
87 03/03/2024 06:18:20 03/03/2024 06:18:20
88 03/03/2024 06:18:20 03/03/2024 06:18:20
89 03/03/2024 06:18:20 03/03/2024 06:18:20
90 03/03/2024 06:18:20 03/03/2024 06:18:20
91 03/03/2024 06:18:20 03/03/2024 06:18:20
92 03/03/2024 06:18:20 03/03/2024 06:18:20
93 03/03/2024 06:18:20 03/03/2024 06:18:20
94 03/03/2024 06:18:20 03/03/2024 06:18:20
95 03/03/2024 06:18:20 03/03/2024 06:18:20
96 03/03/2024 06:18:20 03/03/2024 06:18:20
97 03/03/2024 06:18:20 03/03/2024 06:18:20
98 03/03/2024 06:18:20 03/03/2024 06:18:20
99 03/03/2024 06:18:20 03/03/2024 06:18:20
100 03/03/2024 06:18:20 03/03/2024 06:18:20
101 03/03/2024 06:18:20 03/03/2024 06:18:20
102 03/03/2024 06:18:20 03/03/2024 06:18:20
103 03/03/2024 06:18:20 03/03/2024 06:18:20
104 03/03/2024 06:18:20 03/03/2024 06:18:20
105 03/03/2024 06:18:20 03/03/2024 06:18:20
106 03/03/2024 06:18:20 03/03/2024 06:18:20
107 03/03/2024 06:18:20 03/03/2024 06:18:20
108 03/03/2024 06:18:20 03/03/2024 06:18:20
109 03/03/2024 06:18:20 03/03/2024 06:18:20
110 03/03/2024 06:18:20 03/03/2024 06:18:20
111 03/03/2024 06:18:20 03/03/2024 06:18:20
112 03/03/2024 06:18:20 03/03/2024 06:18:20
113 03/03/2024 06:18:20 03/03/2024 06:18:20
114 03/03/2024 06:18:20 03/03/2024 06:18:20
115 03/03/2024 06:18:20 03/03/2024 06:18:20
116 03/03/2024 06:18:20 03/03/2024 06:18:20
117 03/03/2024 06:18:20 03/03/2024 06:18:20
118 03/03/2024 06:18:20 03/03/2024 06:18:20
119 03/03/2024 06:18:20 03/03/2024 06:18:20
120 03/03/2024 06:18:20 03/03/2024 06:18:20
121 03/03/2024 06:18:20 03/03/2024 06:18:20
122 03/03/2024 06:18:20 03/03/2024 06:18:20
123 03/03/2024 06:18:20 03/03/2024 06:18:20
124 03/03/2024 06:18:20 03/03/2024 06:18:20
125 03/03/2024 06:18:20 03/03/2024 06:18:20
126 03/03/2024 06:18:20 03/03/2024 06:18:20
127 03/03/2024 06:18:20 03/03/2024 06:18:20
128 03/03/2024 06:18:20 03/03/2024 06:18:20
129 03/03/2024 06:18:20 03/03/2024 06:18:20
130 03/03/2024 06:18:20 03/03/2024 06:18:20
131 03/03/2024 06:18:20 03/03/2024 06:18:20
132 03/03/2024 06:18:20 03/03/2024 06:18:20
133 03/03/2024 06:18:20 03/03/2024 06:18:20
134 03/03/2024 06:18:20 03/03/2024 06:18:20
135 03/03/2024 06:18:20 03/03/2024 06:18:20
136 03/03/2024 06:18:20 03/03/2024 06:18:20
137 03/03/2024 06:18:20 03/03/2024 06:18:20
138 03/03/2024 06:18:20 03/03/2024 06:18:20
139 03/03/2024 06:18:20 03/03/2024 06:18:20
140 03/03/2024 06:18:20 03/03/2024 06:18:20
141 03/03/2024 06:18:20 03/03/2024 06:18:20
142 03/03/2024 06:18:20 03/03/2024 06:18:20
143 03/03/2024 06:18:20 03/03/2024 06:18:20
144 03/03/2024 06:18:20 03/03/2024 06:18:20
145 03/03/2024 06:18:20 03/03/2024 06:18:20
146 03/03/2024 06:18:20 03/03/2024 06:18:20
147 03/03/2024 06:18:20 03/03/2024 06:18:20
148 03/03/2024 06:18:20 03/03/2024 06:18:20
149 03/03/2024 06:18:20 03/03/2024 06:18:20
150 03/03/2024 06:18:20 03/03/2024 06:18:20
151 03/03/2024 06:18:20 03/03/2024 06:18:20
152 03/03/2024 06:18:20 03/03/2024 06:18:20
153 03/03/2024 06:18:20 03/03/2024 06:18:20
154 03/03/2024 06:18:20 03/03/2024 06:18:20
155 03/03/2024 06:18:20 03/03/2024 06:18:20
156 03/03/2024 06:18:20 03/03/2024 06:18:20
157 03/03/2024 06:18:20 03/03/2024 06:18:20
158 03/03/2024 06:18:20 03/03/2024 06:18:20
159 03/03/2024 06:18:20 03/03/2024 06:18:20
160 03/03/2024 06:18:20 03/03/2024 06:18:20
161 03/03/2024 06:18:20 03/03/2024 06:18:20
162 03/03/2024 06:18:20 03/03/2024 06:18:20
163 03/03/2024 06:18:20 03/03/2024 06:18:20
164 03/03/2024 06:18:20 03/03/2024 06:18:20
165 03/03/2024 06:18:20 03/03/2024 06:18:20
166 03/03/2024 06:18:20 03/03/2024 06:18:20
167 03/03/2024 06:18:20 03/03/2024 06:18:20
168 03/03/2024 06:18:20 03/03/2024 06:18:20
169 03/03/2024 06:18:20 03/03/2024 06:18:20
170 03/03/2024 06:18:20 03/03/2024 06:18:20
171 03/03/2024 06:18:20 03/03/2024 06:18:20
172 03/03/2024 06:18:20 03/03/2024 06:18:20
173 03/03/2024 06:18:20 03/03/2024 06:18:20
174 03/03/2024 06:18:20 03/03/2024 06:18:20
175 03/03/2024 06:18:20 03/03/2024 06:18:20
176 03/03/2024 06:18:20 03/03/2024 06:18:20
177 03/03/2024 06:18:20 03/03/2024 06:18:20
178 03/03/2024 06:18:20 03/03/2024 06:18:20
179 03/03/2024 06:18:20 03/03/2024 06:18:20
180 03/03/2024 06:18:20 03/03/2024 06:18:20
181 03/03/2024 06:18:20 03/03/2024 06:18:20
182 03/03/2024 06:18:20 03/03/2024 06:18:20
183 03/03/2024 06:18:20 03/03/2024 06:18:20
184 03/03/2024 06:18:20 03/03/2024 06:18:20
185 03/03/2024 06:18:20 03/03/2024 06:18:20
186 03/03/2024 06:18:20 03/03/2024 06:18:20
187 03/03/2024 06:18:20 03/03/2024 06:18:20
188 03/03/2024 06:18:20 03/03/2024 06:18:20
189 03/03/2024 06:18:20 03/03/2024 06:18:20
190 03/03/2024 06:18:20 03/03/2024 06:18:20
191 03/03/2024 06:18:20 03/03/2024 06:18:20
192 03/03/2024 06:18:20 03/03/2024 06:18:20
193 03/03/2024 06:18:20 03/03/2024 06:18:20
194 03/03/2024 06:18:20 03/03/2024 06:18:20
195 03/03/2024 06:18:20 03/03/2024 06:18:20
196 03/03/2024 06:18:20 03/03/2024 06:18:20
197 03/03/2024 06:18:20 03/03/2024 06:18:20
198 03/03/2024 06:18:20 03/03/2024 06:18:20
199 03/03/2024 06:18:20 03/03/2024 06:18:20
200 03/03/2024 06:18:20 03/03/2024 06:18:20
201 03/03/2024 06:18:20 03/03/2024 06:18:20
202 03/03/2024 06:18:20 03/03/2024 06:18:20
203 03/03/2024 06:18:20 03/03/2024 06:18:20
204 03/03/2024 06:18:20 03/03/2024 06:18:20
205 03/03/2024 06:18:20 03/03/2024 06:18:20
206 03/03/2024 06:18:20 03/03/2024 06:18:20
207 03/03/2024 06:18:20 03/03/2024 06:18:20
208 03/03/2024 06:18:20 03/03/2024 06:18:20
209 03/03/2024 06:18:20 03/03/2024 06:18:20
210 03/03/2024 06:18:20 03/03/2024 06:18:20
211 03/03/2024 06:18:20 03/03/2024 06:18:20
212 03/03/2024 06:18:20 03/03/2024 06:18:20
213 03/03/2024 06:18:20 03/03/2024 06:18:20
214 03/03/2024 06:18:20 03/03/2024 06:18:20
215 03/03/2024 06:18:20 03/03/2024 06:18:20
216 03/03/2024 06:18:20 03/03/2024 06:18:20
217 03/03/2024 06:18:20 03/03/2024 06:18:20
218 03/03/2024 06:18:20 03/03/2024 06:18:20
219 03/03/2024 06:18:20 03/03/2024 06:18:20
220 03/03/2024 06:18:20 03/03/2024 06:18:20
221 03/03/2024 06:18:20 03/03/2024 06:18:20
222 03/03/2024 06:18:20 03/03/2024 06:18:20
223 03/03/2024 06:18:20 03/03/2024 06:18:20
224 03/03/2024 06:18:20 03/03/2024 06:18:20
225 03/03/2024 06:18:20 03/03/2024 06:18:20
226 03/03/2024 06:18:20 03/03/2024 06:18:20
227 03/03/2024 06:18:20 03/03/2024 06:18:20
228 03/03/2024 06:18:20 03/03/2024 06:18:20
229 03/03/2024 06:18:20 03/03/2024 06:18:20
230 03/03/2024 06:18:20 03/03/2024 06:18:20
231 03/03/2024 06:18:20 03/03/2024 06:18:20
232 03/03/2024 06:18:20 03/03/2024 06:18:20
233 03/03/2024 06:18:20 03/03/2024 06:18:20
234 03/03/2024 06:18:20 03/03/2024 06:18:20
235 03/03/2024 06:18:20 03/03/2024 06:18:20
236 03/03/2024 06:18:20 03/03/2024 06:18:20
237 03/03/2024 06:18:20 03/03/2024 06:18:20
238 03/03/2024 06:18:20 03/03/2024 06:18:20
239 03/03/2024 06:18:20 03/03/2024 06:18:20
240 03/03/2024 06:18:20 03/03/2024 06:18:20
241 03/03/2024 06:18:20 03/03/2024 06:18:20
242 03/03/2024 06:18:20 03/03/2024 06:18:20
243 03/03/2024 06:18:20 03/03/2024 06:18:20
244 03/03/2024 06:18:20 03/03/2024 06:18:20
245 03/03/2024 06:18:20 03/03/2024 06:18:20
246 03/03/2024 06:18:20 03/03/2024 06:18:20
247 03/03/2024 06:18:20 03/03/2024 06:18:20
248 03/03/2024 06:18:20 03/03/2024 06:18:20
249 03/03/2024 06:18:20 03/03/2024 06:18:20
250 03/03/2024 06:18:20 03/03/2024 06:18:20
251 03/03/2024 06:18:20 03/03/2024 06:18:20
252 03/03/2024 06:18:20 03/03/2024 06:18:20
253 03/03/2024 06:18:20 03/03/2024 06:18:20
254 03/03/2024 06:18:20 03/03/2024 06:18:20
255 03/03/2024 06:18:20 03/03/2024 06:18:20
256 03/03/2024 06:18:20 03/03/2024 06:18:20
257 03/03/2024 06:18:20 03/03/2024 06:18:20
258 03/03/2024 06:18:20 03/03/2024 06:18:20
259 03/03/2024 06:18:20 03/03/2024 06:18:20
260 03/03/2024 06:18:20 03/03/2024 06:18:20
261 03/03/2024 06:18:20 03/03/2024 06:18:20
262 03/03/2024 06:18:20 03/03/2024 06:18:20
263 03/03/2024 06:18:20 03/03/2024 06:18:20
264 03/03/2024 06:18:20 03/03/2024 06:18:20
265 03/03/2024 06:18:20 03/03/2024 06:18:20
266 03/03/2024 06:18:20 03/03/2024 06:18:20
267 03/03/2024 06:18:20 03/03/2024 06:18:20
268 03/03/2024 06:18:20 03/03/2024 06:18:20
269 03/03/2024 06:18:20 03/03/2024 06:18:20
270 03/03/2024 06:18:20 03/03/2024 06:18:20
271 03/03/2024 06:18:20 03/03/2024 06:18:20
272 03/03/2024 06:18:20 03/03/2024 06:18:20
273 03/03/2024 06:18:20 03/03/2024 06:18:20
274 03/03/2024 06:18:20 03/03/2024 06:18:20
275 03/03/2024 06:18:20 03/03/2024 06:18:20
276 03/03/2024 06:18:20 03/03/2024 06:18:20
277 03/03/2024 06:18:20 03/03/2024 06:18:20
278 03/03/2024 06:18:20 03/03/2024 06:18:20
279 03/03/2024 06:18:20 03/03/2024 06:18:20
280 03/03/2024 06:18:20 03/03/2024 06:18:20
281 03/03/2024 06:18:20 03/03/2024 06:18:20
282 03/03/2024 06:18:20 03/03/2024 06:18:20
283 03/03/2024 06:18:20 03/03/2024 06:18:20
284 03/03/2024 06:18:20 03/03/2024 06:18:20
285 03/03/2024 06:18:20 03/03/2024 06:18:20
286 03/03/2024 06:18:20 03/03/2024 06:18:20
287 03/03/2024 06:18:20 03/03/2024 06:18:20
288 03/03/2024 06:18:20 03/03/2024 06:18:20
289 03/03/2024 06:18:20 03/03/2024 06:18:20
290 03/03/2024 06:18:20 03/03/2024 06:18:20
291 03/03/2024 06:18:20 03/03/2024 06:18:20
292 03/03/2024 06:18:20 03/03/2024 06:18:20
293 03/03/2024 06:18:20 03/03/2024 06:18:20
294 03/03/2024 06:18:20 03/03/2024 06:18:20
295 03/03/2024 06:18:20 03/03/2024 06:18:20
296 03/03/2024 06:18:20 03/03/2024 06:18:20
297 03/03/2024 06:18:20 03/03/2024 06:18:20
298 03/03/2024 06:18:20 03/03/2024 06:18:20
299 03/03/2024 06:18:20 03/03/2024 06:18:20
300 03/03/2024 06:18:20 03/03/2024 06:18:20
301 03/03/2024 06:18:20 03/03/2024 06:18:20
302 03/03/2024 06:18:20 03/03/2024 06:18:20
303 03/03/2024 06:18:20 03/03/2024 06:18:20
304 03/03/2024 06:18:20 03/03/2024 06:18:20
305 03/03/2024 06:18:20 03/03/2024 06:18:20
306 03/03/2024 06:18:20 03/03/2024 06:18:20
307 03/03/2024 06:18:20 03/03/2024 06:18:20
308 03/03/2024 06:18:20 03/03/2024 06:18:20
309 03/03/2024 06:18:20 03/03/2024 06:18:20
310 03/03/2024 06:18:20 03/03/2024 06:18:20
311 03/03/2024 06:18:20 03/03/2024 06:18:20
312 03/03/2024 06:18:20 03/03/2024 06:18:20
313 03/03/2024 06:18:20 03/03/2024 06:18:20
314 03/03/2024 06:18:20 03/03/2024 06:18:20
315 03/03/2024 06:18:20 03/03/2024 06:18:20
316 03/03/2024 06:18:20 03/03/2024 06:18:20
317 03/03/2024 06:18:20 03/03/2024 06:18:20
318 03/03/2024 06:18:20 03/03/2024 06:18:20
319 03/03/2024 06:18:20 03/03/2024 06:18:20
320 03/03/2024 06:18:20 03/03/2024 06:18:20
321 03/03/2024 06:18:20 03/03/2024 06:18:20
322 03/03/2024 06:18:20 03/03/2024 06:18:20
323 03/03/2024 06:18:20 03/03/2024 06:18:20
324 03/03/2024 06:18:20 03/03/2024 06:18:20
325 03/03/2024 06:18:20 03/03/2024 06:18:20
326 03/03/2024 06:18:20 03/03/2024 06:18:20
327 03/03/2024 06:18:20 03/03/2024 06:18:20
328 03/03/2024 06:18:20 03/03/2024 06:18:20
329 03/03/2024 06:18:20 03/03/2024 06:18:20
330 03/03/2024 06:18:20 03/03/2024 06:18:20
331 03/03/2024 06:18:20 03/03/2024 06:18:20
332 03/03/2024 06:18:20 03/03/2024 06:18:20
333 03/03/2024 06:18:20 03/03/2024 06:18:20
334 03/03/2024 06:18:20 03/03/2024 06:18:20
335 03/03/2024 06:18:20 03/03/2024 06:18:20
336 03/03/2024 06:18:20 03/03/2024 06:18:20
337 03/03/2024 06:18:20 03/03/2024 06:18:20
338 03/03/2024 06:18:20 03/03/2024 06:18:20
339 03/03/2024 06:18:20 03/03/2024 06:18:20
340 03/03/2024 06:18:20 03/03/2024 06:18:20
341 03/03/2024 06:18:20 03/03/2024 06:18:20
342 03/03/2024 06:18:20 03/03/2024 06:18:20
343 03/03/2024 06:18:20 03/03/2024 06:18:20
344 03/03/2024 06:18:20 03/03/2024 06:18:20
345 03/03/2024 06:18:20 03/03/2024 06:18:20
346 03/03/2024 06:18:20 03/03/2024 06:18:20
347 03/03/2024 06:18:20 03/03/2024 06:18:20
348 03/03/2024 06:18:20 03/03/2024 06:18:20
349 03/03/2024 06:18:20 03/03/2024 06:18:20
350 03/03/2024 06:18:20 03/03/2024 06:18:20
351 03/03/2024 06:18:20 03/03/2024 06:18:20
352 03/03/2024 06:18:20 03/03/2024 06:18:20
353 03/03/2024 06:18:20 03/03/2024 06:18:20
354 03/03/2024 06:18:20 03/03/2024 06:18:20
355 03/03/2024 06:18:20 03/03/2024 06:18:20
356 03/03/2024 06:18:20 03/03/2024 06:18:20
357 03/03/2024 06:18:20 03/03/2024 06:18:20
358 03/03/2024 06:18:20 03/03/2024 06:18:20
359 03/03/2024 06:18:20 03/03/2024 06:18:20
360 03/03/2024 06:18:20 03/03/2024 06:18:20
361 03/03/2024 06:18:20 03/03/2024 06:18:20
362 03/03/2024 06:18:20 03/03/2024 06:18:20
363 03/03/2024 06:18:20 03/03/2024 06:18:20
364 03/03/2024 06:18:20 03/03/2024 06:18:20
365 03/03/2024 06:18:20 03/03/2024 06:18:20
366 03/03/2024 06:18:20 03/03/2024 06:18:20
367 03/03/2024 06:18:20 03/03/2024 06:18:20
368 03/03/2024 06:18:20 03/03/2024 06:18:20
369 03/03/2024 06:18:20 03/03/2024 06:18:20
370 03/03/2024 06:18:20 03/03/2024 06:18:20
371 03/03/2024 06:18:20 03/03/2024 06:18:20
372 03/03/2024 06:18:20 03/03/2024 06:18:20
373 03/03/2024 06:18:20 03/03/2024 06:18:20
374 03/03/2024 06:18:20 03/03/2024 06:18:20
375 03/03/2024 06:18:20 03/03/2024 06:18:20
376 03/03/2024 06:18:20 03/03/2024 06:18:20
377 03/03/2024 06:18:20 03/03/2024 06:18:20
378 03/03/2024 06:18:20 03/03/2024 06:18:20
379 03/03/2024 06:18:20 03/03/2024 06:18:20
380 03/03/2024 06:18:20 03/03/2024 06:18:20
381 03/03/2024 06:18:20 03/03/2024 06:18:20
382 03/03/2024 06:18:20 03/03/2024 06:18:20
383 03/03/2024 06:18:20 03/03/2024 06:18:20
384 03/03/2024 06:18:20 03/03/2024 06:18:20
385 03/03/2024 06:18:20 03/03/2024 06:18:20
386 03/03/2024 06:18:20 03/03/2024 06:18:20
387 03/03/2024 06:18:20 03/03/2024 06:18:20
388 03/03/2024 06:18:20 03/03/2024 06:18:20
389 03/03/2024 06:18:20 03/03/2024 06:18:20
390 03/03/2024 06:18:20 03/03/2024 06:18:20
391 03/03/2024 06:18:20 03/03/2024 06:18:20
392 03/03/2024 06:18:20 03/03/2024 06:18:20
393 03/03/2024 06:18:20 03/03/2024 06:18:20
394 03/03/2024 06:18:20 03/03/2024 06:18:20
395 03/03/2024 06:18:20 03/03/2024 06:18:20
396 03/03/2024 06:18:20 03/03/2024 06:18:20
397 03/03/2024 06:18:20 03/03/2024 06:18:20
398 03/03/2024 06:18:20 03/03/2024 06:18:20
399 03/03/2024 06:18:20 03/03/2024 06:18:20
400 03/03/2024 06:18:20 03/03/2024 06:18:20
401 03/03/2024 06:18:20 03/03/2024 06:18:20
402 03/03/2024 06:18:20 03/03/2024 06:18:20
403 03/03/2024 06:18:20 03/03/2024 06:18:20
404 03/03/2024 06:18:20 03/03/2024 06:18:20
405 03/03/2024 06:18:20 03/03/2024 06:18:20
406 03/03/2024 06:18:20 03/03/2024 06:18:20
407 03/03/2024 06:18:20 03/03/2024 06:18:20
408 03/03/2024 06:18:20 03/03/2024 06:18:20
409 03/03/2024 06:18:20 03/03/2024 06:18:20
410 03/03/2024 06:18:20 03/03/2024 06:18:20
411 03/03/2024 06:18:20 03/03/2024 06:18:20
412 03/03/2024 06:18:20 03/03/2024 06:18:20
413 03/03/2024 06:18:20 03/03/2024 06:18:20
414 03/03/2024 06:18:20 03/03/2024 06:18:20
415 03/03/2024 06:18:20 03/03/2024 06:18:20
416 03/03/2024 06:18:20 03/03/2024 06:18:20
417 03/03/2024 06:18:20 03/03/2024 06:18:20
418 03/03/2024 06:18:20 03/03/2024 06:18:20
419 03/03/2024 06:18:20 03/03/2024 06:18:20
420 03/03/2024 06:18:20 03/03/2024 06:18:20
421 03/03/2024 06:18:20 03/03/2024 06:18:20
422 03/03/2024 06:18:20 03/03/2024 06:18:20
423 03/03/2024 06:18:20 03/03/2024 06:18:20
424 03/03/2024 06:18:20 03/03/2024 06:18:20
425 03/03/2024 06:18:20 03/03/2024 06:18:20
426 03/03/2024 06:18:20 03/03/2024 06:18:20
427 03/03/2024 06:18:20 03/03/2024 06:18:20
428 03/03/2024 06:18:20 03/03/2024 06:18:20
429 03/03/2024 06:18:20 03/03/2024 06:18:20
430 03/03/2024 06:18:20 03/03/2024 06:18:20
431 03/03/2024 06:18:20 03/03/2024 06:18:20
432 03/03/2024 06:18:20 03/03/2024 06:18:20
433 03/03/2024 06:18:20 03/03/2024 06:18:20
434 03/03/2024 06:18:20 03/03/2024 06:18:20
435 03/03/2024 06:18:20 03/03/2024 06:18:20
436 03/03/2024 06:18:20 03/03/2024 06:18:20
437 03/03/2024 06:18:20 03/03/2024 06:18:20
438 03/03/2024 06:18:20 03/03/2024 06:18:20
439 03/03/2024 06:18:20 03/03/2024 06:18:20
440 03/03/2024 06:18:20 03/03/2024 06:18:20
441 03/03/2024 06:18:20 03/03/2024 06:18:20
442 03/03/2024 06:18:20 03/03/2024 06:18:20
443 03/03/2024 06:18:20 03/03/2024 06:18:20
444 03/03/2024 06:18:20 03/03/2024 06:18:20
445 03/03/2024 06:18:20 03/03/2024 06:18:20
446 03/03/2024 06:18:20 03/03/2024 06:18:20
447 03/03/2024 06:18:20 03/03/2024 06:18:20
448 03/03/2024 06:18:20 03/03/2024 06:18:20
449 03/03/2024 06:18:20 03/03/2024 06:18:20
450 03/03/2024 06:18:20 03/03/2024 06:18:20
451 03/03/2024 06:18:20 03/03/2024 06:18:20
452 03/03/2024 06:18:20 03/03/2024 06:18:20
453 03/03/2024 06:18:20 03/03/2024 06:18:20
454 03/03/2024 06:18:20 03/03/2024 06:18:20
455 03/03/2024 06:18:20 03/03/2024 06:18:20

In [32]:
df_stops

        id            startTime              endTime downtime  \
0        0  03/02/2024 15:09:13  03/02/2024 15:32:13    24843
1        1  03/02/2024 15:34:53  03/02/2024 15:45:13    24843
2        2  03/02/2024 15:53:53  03/02/2024 16:38:34    24843
3        3  03/02/2024 16:48:14  03/02/2024 17:07:34    24843
4        4  03/02/2024 17:15:54  03/02/2024 17:32:34    24843
5        5  03/02/2024 17:36:14  03/02/2024 18:23:34    24843
6        6  03/02/2024 18:30:15  03/02/2024 19:39:35    24843
7        7  03/02/2024 19:43:15  03/02/2024 19:56:35    24843
8        8  03/02/2024 19:59:55  03/02/2024 20:59:36    24843
9        9  03/02/2024 21:02:56  03/02/2024 21:29:16    24843
10      10  03/02/2024 21:35:36  03/02/2024 22:59:57    24843
11      11  03/02/2024 23:00:17  03/02/2024 23:08:17     3200
12      12  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
13      13  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
14      14  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
15      15  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
16      16  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
17      17  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
18      18  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
19      19  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
20      20  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
21      21  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
22      22  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
23      23  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
24      24  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
25      25  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
26      26  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
27      27  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
28      28  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
29      29  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
30      30  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
31      31  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
32      32  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
33      33  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
34      34  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
35      35  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
36      36  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
37      37  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
38      38  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
39      39  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
40      40  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
41      41  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
42      42  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
43      43  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
44      44  03/02/2024 23:52:37  03/02/2024 23:08:17     3200
45      45  03/02/2024 23:10:17  03/02/2024 23:14:17     3200
46      46  03/02/2024 23:15:17  03/02/2024 23:49:37     3200
47      47  03/02/2024 23:52:37  03/02/2024 23:59:57     3200
48      48  03/03/2024 00:00:17  03/03/2024 00:09:57    17243
49      49  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
50      50  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
51      51  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
52      52  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
53      53  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
54      54  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
55      55  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
56      56  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
57      57  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
58      58  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
59      59  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
60      60  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
61      61  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
62      62  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
63      63  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
64      64  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
65      65  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
66      66  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
67      67  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
68      68  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
69      69  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
70      70  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
71      71  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
72      72  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
73      73  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
74      74  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
75      75  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
76      76  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
77      77  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
78      78  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
79      79  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
80      80  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
81      81  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
82      82  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
83      83  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
84      84  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
85      85  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
86      86  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
87      87  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
88      88  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
89      89  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
90      90  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
91      91  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
92      92  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
93      93  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
94      94  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
95      95  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
96      96  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
97      97  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
98      98  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
99      99  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
100    100  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
101    101  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
102    102  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
103    103  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
104    104  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
105    105  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
106    106  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
107    107  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
108    108  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
109    109  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
110    110  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
111    111  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
112    112  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
113    113  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
114    114  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
115    115  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
116    116  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
117    117  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
118    118  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
119    119  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
120    120  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
121    121  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
122    122  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
123    123  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
124    124  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
125    125  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
126    126  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
127    127  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
128    128  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
129    129  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
130    130  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
131    131  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
132    132  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
133    133  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
134    134  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
135    135  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
136    136  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
137    137  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
138    138  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
139    139  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
140    140  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
141    141  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
142    142  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
143    143  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
144    144  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
145    145  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
146    146  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
147    147  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
148    148  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
149    149  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
150    150  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
151    151  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
152    152  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
153    153  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
154    154  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
155    155  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
156    156  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
157    157  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
158    158  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
159    159  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
160    160  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
161    161  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
162    162  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
163    163  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
164    164  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
165    165  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
166    166  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
167    167  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
168    168  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
169    169  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
170    170  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
171    171  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
172    172  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
173    173  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
174    174  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
175    175  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
176    176  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
177    177  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
178    178  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
179    179  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
180    180  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
181    181  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
182    182  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
183    183  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
184    184  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
185    185  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
186    186  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
187    187  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
188    188  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
189    189  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
190    190  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
191    191  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
192    192  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
193    193  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
194    194  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
195    195  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
196    196  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
197    197  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
198    198  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
199    199  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
200    200  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
201    201  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
202    202  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
203    203  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
204    204  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
205    205  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
206    206  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
207    207  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
208    208  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
209    209  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
210    210  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
211    211  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
212    212  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
213    213  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
214    214  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
215    215  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
216    216  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
217    217  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
218    218  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
219    219  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
220    220  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
221    221  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
222    222  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
223    223  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
224    224  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
225    225  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
226    226  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
227    227  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
228    228  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
229    229  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
230    230  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
231    231  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
232    232  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
233    233  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
234    234  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
235    235  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
236    236  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
237    237  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
238    238  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
239    239  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
240    240  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
241    241  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
242    242  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
243    243  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
244    244  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
245    245  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
246    246  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
247    247  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
248    248  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
249    249  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
250    250  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
251    251  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
252    252  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
253    253  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
254    254  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
255    255  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
256    256  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
257    257  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
258    258  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
259    259  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
260    260  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
261    261  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
262    262  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
263    263  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
264    264  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
265    265  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
266    266  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
267    267  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
268    268  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
269    269  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
270    270  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
271    271  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
272    272  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
273    273  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
274    274  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
275    275  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
276    276  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
277    277  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
278    278  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
279    279  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
280    280  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
281    281  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
282    282  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
283    283  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
284    284  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
285    285  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
286    286  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
287    287  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
288    288  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
289    289  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
290    290  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
291    291  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
292    292  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
293    293  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
294    294  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
295    295  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
296    296  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
297    297  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
298    298  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
299    299  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
300    300  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
301    301  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
302    302  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
303    303  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
304    304  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
305    305  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
306    306  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
307    307  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
308    308  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
309    309  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
310    310  03/03/2024 00:38:58  03/03/2024 00:41:18    17243
311    311  03/03/2024 01:22:58  03/03/2024 01:44:18    17243
312    312  03/03/2024 01:49:58  03/03/2024 01:52:38    17243
313    313  03/03/2024 01:53:18  03/03/2024 02:13:38    17243
314    314  03/03/2024 02:14:18  03/03/2024 02:21:58    17243
315    315  03/03/2024 02:23:18  03/03/2024 02:33:19    17243
316    316  03/03/2024 02:38:59  03/03/2024 02:46:19    17243
317    317  03/03/2024 02:57:59  03/03/2024 03:28:39    17243
318    318  03/03/2024 03:42:59  03/03/2024 00:09:57    17243
319    319  03/03/2024 00:15:17  03/03/2024 00:35:38    17243
320    320  03/03/2024 00:38:58  03/03/2024 00:41:18    17243

In [12]:
import requests
url = f"https://oeeb-k.pakistanautomation.com.pk/api/curruntStatus/getspeedDatabyTime?deviceName=MiraFlex%201&startTime=04/09/2024%2007:00:07&endTime=04/09/2024%2014:46:31"
response = requests.get(url)
data=response.json()['data']
print(data)

[{'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:00:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:00:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:00:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:01:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:01:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:01:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:02:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:02:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:02:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:03:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:03:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:03:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:04:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:04:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:04:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:05:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:05:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:05:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:06:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:06:27'}, {'deviceStatus': 1, 'machineSpeed': 23, 'timestamp': '04/09/2024 07:06:47'}, {'deviceStatus': 1, 'machineSpeed': 60, 'timestamp': '04/09/2024 07:07:07'}, {'deviceStatus': 1, 'machineSpeed': 59, 'timestamp': '04/09/2024 07:07:27'}, {'deviceStatus': 1, 'machineSpeed': 59, 'timestamp': '04/09/2024 07:07:47'}, {'deviceStatus': 1, 'machineSpeed': 59, 'timestamp': '04/09/2024 07:08:07'}, {'deviceStatus': 1, 'machineSpeed': 59, 'timestamp': '04/09/2024 07:08:27'}, {'deviceStatus': 1, 'machineSpeed': 60, 'timestamp': '04/09/2024 07:08:47'}, {'deviceStatus': 1, 'machineSpeed': 59, 'timestamp': '04/09/2024 07:09:07'}, {'deviceStatus': 1, 'machineSpeed': 59, 'timestamp': '04/09/2024 07:09:27'}, {'deviceStatus': 1, 'machineSpeed': 81, 'timestamp': '04/09/2024 07:09:47'}, {'deviceStatus': 1, 'machineSpeed': 101, 'timestamp': '04/09/2024 07:10:07'}, {'deviceStatus': 1, 'machineSpeed': 99, 'timestamp': '04/09/2024 07:10:27'}, {'deviceStatus': 1, 'machineSpeed': 89, 'timestamp': '04/09/2024 07:10:47'}, {'deviceStatus': 1, 'machineSpeed': 116, 'timestamp': '04/09/2024 07:11:07'}, {'deviceStatus': 1, 'machineSpeed': 150, 'timestamp': '04/09/2024 07:11:27'}, {'deviceStatus': 1, 'machineSpeed': 146, 'timestamp': '04/09/2024 07:11:47'}, {'deviceStatus': 1, 'machineSpeed': 170, 'timestamp': '04/09/2024 07:12:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:13:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:13:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:13:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:14:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:14:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:14:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:15:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:15:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:15:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:16:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:16:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:16:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:17:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:17:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:17:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:18:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:18:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:18:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:19:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:19:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:19:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:20:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:20:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:20:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:21:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:21:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:21:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:22:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:22:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:22:47'}, {'deviceStatus': 1, 'machineSpeed': 12, 'timestamp': '04/09/2024 07:23:07'}, {'deviceStatus': 1, 'machineSpeed': 163, 'timestamp': '04/09/2024 07:23:27'}, {'deviceStatus': 1, 'machineSpeed': 317, 'timestamp': '04/09/2024 07:23:47'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:24:07'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:24:27'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:24:47'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:25:07'}, {'deviceStatus': 0, 'machineSpeed': 30, 'timestamp': '04/09/2024 07:25:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:25:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:26:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:26:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:26:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:27:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:27:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:27:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:28:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:28:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:28:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:29:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:29:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:29:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:30:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:30:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:30:47'}, {'deviceStatus': 1, 'machineSpeed': 70, 'timestamp': '04/09/2024 07:31:07'}, {'deviceStatus': 1, 'machineSpeed': 327, 'timestamp': '04/09/2024 07:31:27'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:31:47'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:32:07'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:32:27'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:32:47'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:33:07'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:33:27'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:33:47'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:34:07'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:34:27'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:34:47'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:35:07'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:35:27'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:35:47'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:36:07'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:36:27'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:36:47'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:37:07'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:37:27'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:37:47'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:38:07'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:38:27'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:38:47'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:39:07'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:39:27'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:39:47'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:40:07'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:40:27'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:40:47'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:41:07'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:41:27'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:41:47'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:42:07'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:42:27'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:42:47'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:43:07'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:43:27'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:43:47'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:44:07'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:44:27'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:44:47'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:45:07'}, {'deviceStatus': 1, 'machineSpeed': 399, 'timestamp': '04/09/2024 07:45:27'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:45:47'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:46:07'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:46:27'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 07:46:47'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:47:07'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 07:47:27'}, {'deviceStatus': 1, 'machineSpeed': 453, 'timestamp': '04/09/2024 07:47:47'}, {'deviceStatus': 1, 'machineSpeed': 501, 'timestamp': '04/09/2024 07:48:07'}, {'deviceStatus': 1, 'machineSpeed': 501, 'timestamp': '04/09/2024 07:48:27'}, {'deviceStatus': 1, 'machineSpeed': 501, 'timestamp': '04/09/2024 07:48:47'}, {'deviceStatus': 1, 'machineSpeed': 497, 'timestamp': '04/09/2024 07:49:07'}, {'deviceStatus': 1, 'machineSpeed': 410, 'timestamp': '04/09/2024 07:49:27'}, {'deviceStatus': 0, 'machineSpeed': 50, 'timestamp': '04/09/2024 07:49:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:50:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:50:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:50:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:51:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:51:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:51:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:52:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:52:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:52:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:53:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:53:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:53:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:54:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:54:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:54:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:55:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:55:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:55:47'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:56:07'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:56:27'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:56:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:57:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:57:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:57:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:58:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:58:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:58:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:59:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:59:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 07:59:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:00:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:00:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:00:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:01:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:01:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:01:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:02:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:02:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:02:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:03:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:03:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:03:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:04:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:04:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:04:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:05:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:05:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:05:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:06:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:06:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:06:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:07:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:07:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:07:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:08:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:08:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:08:48'}, {'deviceStatus': 1, 'machineSpeed': 81, 'timestamp': '04/09/2024 08:09:08'}, {'deviceStatus': 1, 'machineSpeed': 89, 'timestamp': '04/09/2024 08:09:28'}, {'deviceStatus': 1, 'machineSpeed': 171, 'timestamp': '04/09/2024 08:09:48'}, {'deviceStatus': 1, 'machineSpeed': 338, 'timestamp': '04/09/2024 08:10:08'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:10:28'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:10:48'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:11:08'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:11:28'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:11:48'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:12:08'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:12:28'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:12:48'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:13:08'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:13:28'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:13:48'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:14:08'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:14:28'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:15:28'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:15:48'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:16:08'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:16:28'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:16:48'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:17:08'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:17:28'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:17:48'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:18:08'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:18:28'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:18:48'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:19:08'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:19:28'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:19:48'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:20:08'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:20:28'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:20:48'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:21:08'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:21:28'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:21:48'}, {'deviceStatus': 1, 'machineSpeed': 398, 'timestamp': '04/09/2024 08:22:08'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:22:28'}, {'deviceStatus': 1, 'machineSpeed': 401, 'timestamp': '04/09/2024 08:22:48'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:23:08'}, {'deviceStatus': 1, 'machineSpeed': 400, 'timestamp': '04/09/2024 08:23:28'}, {'deviceStatus': 0, 'machineSpeed': 356, 'timestamp': '04/09/2024 08:23:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:24:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:24:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:24:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:25:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:25:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:25:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:26:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:26:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:26:48'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:27:08'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:27:28'}, {'deviceStatus': 0, 'machineSpeed': 0, 'timestamp': '04/09/2024 08:27:48'}, {'devic

In [22]:
df_c[df_c["orderId"]==536]

,id,deviceName,productCount,deviceStatus,poNumber,skuName,skuTarget,shiftName,teamName,distributerName,plannedStart,plannedEnd,orderCompletionStatus,shippableProduct,scrap,upTime,downTime,orderId,shiftStartTime,shiftEndTime,qtyInKg,timestamp
98,519,MiraFlex 1,68144,0,,PET (400),400,B,,,03/02/2024 15:07:13,03/02/2024 15:08:53,1,0,0,20,80,536,15:00:00,23:00:00,0,03/02/2024 15:08:53
99,520,MiraFlex 1,84628,0,620069-A,PET (400),400,B,,,03/02/2024 15:09:13,03/02/2024 22:59:57,1,0,0,3401,24843,536,15:00:00,23:00:00,15621.425988306082,03/02/2024 22:59:57
100,521,MiraFlex 1,1362,0,620069-A,PET (400),400,C,,,03/02/2024 23:00:17,03/02/2024 23:59:57,1,0,0,380,3200,536,23:00:00,07:00:00,251.47455423939877,03/02/2024 23:59:57
101,522,MiraFlex 1,37035,0,620069-A,PET (400),400,C,,,03/03/2024 00:00:17,03/03/2024 06:18:20,1,0,0,5440,17243,536,23:00:00,07:00:00,6836.196048912367,03/03/2024 06:18:20