In [1]:
import pymysql
import pandas as pd

connection=pymysql.connect(
    host="s13.hosterpk.com",
    user="pakis104_owaisJaved",
    password="Developers123@",
    database="pakis104_oee_kompass"
)
df_c = pd.read_sql_query("SELECT * FROM CompleteOrders", connection)
df_d = pd.read_sql_query("SELECT * FROM DeviceData", connection)
print(df_c)
print(df_d)
connection.close()

OperationalError: (1045, "Access denied for user 'pakis104_owaisJaved'@'103.244.178.98' (using password: YES)")

In [4]:
df_running.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               3000 non-null   int64
 1   startTime        0 non-null      object
 2   endTime          0 non-null      object
 3   uptime           0 non-null      object
 4   orderStart       0 non-null      object
 5   orderEnd         0 non-null      object
 6   childDeviceName  0 non-null      object
 7   deviceName       0 non-null      object
 8   shiftName        0 non-null      object
 9   shiftStartTime   0 non-null      object
 10  shiftEndTime     0 non-null      object
 11  deviceDataId     0 non-null      object
 12  orderId          0 non-null      object
dtypes: int64(1), object(12)
memory usage: 304.8+ KB

In [2]:
df_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     201 non-null    int64
 1   deviceName             201 non-null    object
 2   productCount           201 non-null    int64
 3   deviceStatus           201 non-null    int64
 4   poNumber               201 non-null    object
 5   skuName                201 non-null    object
 6   skuTarget              201 non-null    int64
 7   shiftName              201 non-null    object
 8   teamName               201 non-null    object
 9   distributerName        201 non-null    object
 10  plannedStart           201 non-null    object
 11  plannedEnd             201 non-null    object
 12  orderCompletionStatus  201 non-null    int64
 13  shippableProduct       201 non-null    int64
 14  scrap                  201 non-null    int64
 15  upTime                 201 non-null    int64
 16  downTime               201 non-null    int64
 17  orderId                201 non-null    int64
 18  shiftStartTime         201 non-null    object
 19  shiftEndTime           201 non-null    object
 20  qtyInKg                201 non-null    object
 21  timestamp              201 non-null    object
dtypes: int64(10), object(12)
memory usage: 34.7+ KB

In [3]:
df_running=pd.DataFrame(columns=["id","startTime","endTime","uptime","orderStart","orderEnd","childDeviceName","deviceName","shiftName","shiftStartTime","shiftEndTime","deviceDataId","orderId"])

df_running["id"]=range(3000)

In [16]:
df_running['childDeviceName']="MiraFlex 1"
df_running['deviceName']="MiraFlex 1"
j=0
for i in range(len(df_c)):
    df_running.iloc[j,12]=df_c.iloc[i,17]
    df_running.iloc[j,4]=df_c.iloc[i,10]
    df_running.iloc[j,5]=df_c.iloc[i,11]
    #df_running.iloc[j,3]=df_c.iloc[i,16]
    df_running.iloc[j,8]=df_c.iloc[i,7]
    df_running.iloc[j,9]=df_c.iloc[i,18]
    df_running.iloc[j,10]=df_c.iloc[i,19]
    #df_running.iloc[j,22]=df_c.iloc[i,5]
    df_combine = pd.merge(df_running, df_d, left_on="orderId", right_on="orderId", how="inner", suffixes=("_running", "_d"))
    last=0
    
    for k in range(len(df_combine)): 
        if ((str(df_running.iloc[j,4])<=df_combine.iloc[k,24]) and (df_running.iloc[j,5]>=df_combine.iloc[k,24])):
            current=df_combine.iloc[k,15]
            if ((current!=last)and(current==1)):
                df_running.iloc[j,1]=df_combine.iloc[k,24]
                j+=1   
            if ((current!=last)and(current==0)): 
                df_running.iloc[j,2]=df_combine.iloc[k,24]
            last=df_combine.iloc[k,15] 
              
#df_combine

In [58]:
df_stops.to_csv("stops1.csv")

In [12]:
df_combine

,id_running,startTime,endTime,uptime,orderStart,orderEnd,childDeviceName,deviceName_running,shiftName,shiftStartTime,shiftEndTime,deviceDataId,orderId,id_d,deviceName_d,deviceStatus,productCount,poNumber,poStart,poEnd,skuName,skuTarget,teamName,distributerName,timestamp,scrap,causeOne,machineSpeed,qtyInKg,stopId,completeOrderId
0,0,NaN,NaN,NaN,04/09/2024 07:00:07,04/09/2024 14:46:31,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,490550,MiraFlex 1,1,1103,118289,,,LDPE (400),400,,,03/19/2024 11:54:21,0,,499,72.14775858978153,0,0
1,0,NaN,NaN,NaN,04/09/2024 07:00:07,04/09/2024 14:46:31,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,490551,MiraFlex 1,1,1270,118289,,,LDPE (400),400,,,03/19/2024 11:54:41,0,,501,83.06273681897319,0,0
2,0,NaN,NaN,NaN,04/09/2024 07:00:07,04/09/2024 14:46:31,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,490552,MiraFlex 1,1,1437,118289,,,LDPE (400),400,,,03/19/2024 11:55:01,0,,499,93.95296453063833,0,0
3,0,NaN,NaN,NaN,04/09/2024 07:00:07,04/09/2024 14:46:31,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,490553,MiraFlex 1,1,1603,118289,,,LDPE (400),400,,,03/19/2024 11:55:21,0,,499,104.84319224230346,0,0
4,0,NaN,NaN,NaN,04/09/2024 07:00:07,04/09/2024 14:46:31,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,490554,MiraFlex 1,1,1770,118289,,,LDPE (400),400,,,03/19/2024 11:55:41,0,,501,115.75817047149509,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68620,0,NaN,NaN,NaN,04/09/2024 07:00:07,04/09/2024 14:46:31,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,559170,MiraFlex 1,0,50386,118289,,,LDPE (400),400,,,04/09/2024 14:45:11,0,,0,3295.38708541352,0,0
68621,0,NaN,NaN,NaN,04/09/2024 07:00:07,04/09/2024 14:46:31,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,559171,MiraFlex 1,0,50386,118289,,,LDPE (400),400,,,04/09/2024 14:45:31,0,,0,3295.38708541352,0,0
68622,0,NaN,NaN,NaN,04/09/2024 07:00:07,04/09/2024 14:46:31,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,559172,MiraFlex 1,0,50386,118289,,,LDPE (400),400,,,04/09/2024 14:45:51,0,,0,3295.38708541352,0,0
68623,0,NaN,NaN,NaN,04/09/2024 07:00:07,04/09/2024 14:46:31,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,559173,MiraFlex 1,0,50386,118289,,,LDPE (400),400,,,04/09/2024 14:46:11,0,,0,3295.38708541352,0,0
68624,0,NaN,NaN,NaN,04/09/2024 07:00:07,04/09/2024 14:46:31,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,559174,MiraFlex 1,0,50386,118289,,,LDPE (400),400,,,04/09/2024 14:46:31,0,,0,3295.38708541352,0,0

In [56]:
df_stops

,id,startTime,endTime,downtime,orderStart,orderEnd,stopUpdatedTime,stopUpdatedBy,categoryName,causeOne,causeTwo,causeThree,causeFour,causeFive,childDeviceName,deviceName,shiftName,shiftStartTime,shiftEndTime,deviceDataId,orderId,mainStopId,skuName,comment,reasonOne,reasonTwo,Status
0,0,NaN,NaN,550,12/21/2023 12:48:18,12/21/2023 13:58:59,NaN,NaN,Unplanned,NaN,NaN,NaN,NaN,NaN,MiraFlex 1,MiraFlex 1,A,07:00:00,15:00:00,NaN,544,NaN,Material 1 (Speed 400),NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unplanned,NaN,NaN,NaN,NaN,NaN,MiraFlex 1,MiraFlex 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unplanned,NaN,NaN,NaN,NaN,NaN,MiraFlex 1,MiraFlex 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unplanned,NaN,NaN,NaN,NaN,NaN,MiraFlex 1,MiraFlex 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unplanned,NaN,NaN,NaN,NaN,NaN,MiraFlex 1,MiraFlex 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unplanned,NaN,NaN,NaN,NaN,NaN,MiraFlex 1,MiraFlex 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2996,2996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unplanned,NaN,NaN,NaN,NaN,NaN,MiraFlex 1,MiraFlex 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2997,2997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unplanned,NaN,NaN,NaN,NaN,NaN,MiraFlex 1,MiraFlex 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2998,2998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unplanned,NaN,NaN,NaN,NaN,NaN,MiraFlex 1,MiraFlex 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,2999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unplanned,NaN,NaN,NaN,NaN,NaN,MiraFlex 1,MiraFlex 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
import pymysql
import pandas as pd

connection=pymysql.connect(
    host="s13.hosterpk.com",
    user="pakis104_owaisJaved",
    password="Developers123@",
    database="pakis104_oee_kompass"
)
df_c = pd.read_sql_query("SELECT * FROM CompleteOrders", connection)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17656\1457371205.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_c = pd.read_sql_query("SELECT * FROM CompleteOrders", connection)

In [10]:
df_c

,id,deviceName,productCount,deviceStatus,poNumber,skuName,skuTarget,shiftName,teamName,distributerName,plannedStart,plannedEnd,orderCompletionStatus,shippableProduct,scrap,upTime,downTime,orderId,shiftStartTime,shiftEndTime,qtyInKg,timestamp
0,416,MiraFlex 1,108406,0,619815,PET (400),400,C,,,02/01/2024 00:00:15,02/01/2024 06:59:56,1,0,0,99,19294,496,23:00:00,07:00:00,1121.8299033903825,02/01/2024 06:59:56
1,417,MiraFlex 1,153709,0,619815,PET (400),400,A,,,02/01/2024 07:00:19,02/01/2024 14:59:50,1,0,0,187,17607,496,07:00:00,15:00:00,1590.6517581503056,02/01/2024 14:59:50
2,418,MiraFlex 1,189824,0,619815,PET (400),400,B,,,02/01/2024 15:00:09,02/01/2024 22:59:43,1,0,0,865,20089,496,15:00:00,23:00:00,1964.380087563773,02/01/2024 22:59:43
3,419,MiraFlex 1,189824,0,619815,PET (400),400,C,,,02/01/2024 23:00:03,02/02/2024 06:59:59,1,0,0,360,0,496,23:00:00,07:00:00,1964.380087563773,02/02/2024 06:59:59
4,420,MiraFlex 1,193779,0,619815,PET (400),400,A,,,02/02/2024 07:00:18,02/02/2024 14:53:41,1,0,0,28,26774,496,07:00:00,15:00:00,2005.312537540254,02/02/2024 14:53:41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,618,MiraFlex 1,0,0,118289,LDPE (400),400,A,,,04/07/2024 07:00:06,04/07/2024 07:43:46,1,0,0,20,2600,544,07:00:00,15:00:00,0,04/07/2024 07:43:46
197,619,MiraFlex 1,72600,1,118289,LDPE (400),400,A,,,04/08/2024 07:33:35,04/08/2024 14:59:59,1,0,0,11682,15102,544,07:00:00,15:00:00,4748.2690575704255,04/08/2024 14:59:59
198,620,MiraFlex 1,106758,0,118289,LDPE (400),400,B,,,04/08/2024 15:00:19,04/08/2024 22:59:43,1,0,0,16243,12521,544,15:00:00,23:00:00,6982.327854742513,04/08/2024 22:59:43
199,621,MiraFlex 1,97482,0,118289,LDPE (400),400,C,,,04/08/2024 23:00:03,04/09/2024 06:59:47,1,0,0,15041,13743,544,23:00:00,07:00:00,6375.66715016273,04/09/2024 06:59:47
200,622,MiraFlex 1,50386,0,118289,LDPE (400),400,A,,,04/09/2024 07:00:07,04/09/2024 14:46:31,1,0,0,6962,21022,544,07:00:00,15:00:00,3295.38708541352,04/09/2024 14:46:31

In [25]:
#df=pd.ExcelFile("stop1.xlsx")
#df.to_excel("stops1.xlsx")

#df=df.rename(columns={'Unnamed: 0': 'id'})
df

,startTime,endTime,downTime,deviceDataId,Status,orderStart,orderEnd,categoryName,deviceName,childDeviceName,shiftName,shiftStartTime,shiftEndTime,orderId,mainStopId,skuName
0,2024-02-01T15:00:09.000Z,2024-02-01T15:33:10.000Z,1981,348015,Completed,02/01/2024 15:00:09,02/01/2024 22:59:43,Unplanned,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,496,0,PET (400)
1,2024-02-01T15:40:31.000Z,2024-02-01T15:46:10.000Z,339,348136,Completed,02/01/2024 15:00:09,02/01/2024 22:59:43,Unplanned,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,496,0,PET (400)
2,2024-02-01T15:46:50.000Z,2024-02-01T16:07:11.000Z,1221,348155,Completed,02/01/2024 15:00:09,02/01/2024 22:59:43,Unplanned,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,496,0,PET (400)
3,2024-02-01T16:07:51.000Z,2024-02-01T16:09:30.000Z,99,348218,Completed,02/01/2024 15:00:09,02/01/2024 22:59:43,Unplanned,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,496,0,PET (400)
4,2024-02-01T16:10:30.000Z,2024-02-01T16:47:01.000Z,2191,348226,Completed,02/01/2024 15:00:09,02/01/2024 22:59:43,Unplanned,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,496,0,PET (400)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2410,2024-04-08T18:23:21.000Z,2024-04-08T18:26:41.000Z,200,555643,Completed,04/08/2024 15:00:19,04/08/2024 22:59:43,Unplanned,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,544,0,LDPE (400)
2411,2024-04-08T18:43:21.000Z,2024-04-08T19:53:41.000Z,4220,555701,Completed,04/08/2024 15:00:19,04/08/2024 22:59:43,Unplanned,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,544,0,LDPE (400)
2412,2024-04-08T20:53:02.000Z,2024-04-08T20:56:42.000Z,220,556088,Completed,04/08/2024 15:00:19,04/08/2024 22:59:43,Unplanned,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,544,0,LDPE (400)
2413,2024-04-08T21:03:42.000Z,2024-04-08T21:23:02.000Z,1160,556120,Completed,04/08/2024 15:00:19,04/08/2024 22:59:43,Unplanned,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,544,0,LDPE (400)
2414,2024-04-08T22:00:02.000Z,2024-04-08T22:13:23.000Z,801,556287,Completed,04/08/2024 15:00:19,04/08/2024 22:59:43,Unplanned,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,544,0,LDPE (400)

In [28]:
connection=pymysql.connect(
    host="s13.hosterpk.com",
    user="pakis104_owaisJaved",
    password="Developers123@",
    database="pakis104_oee_kompass"
)
df_s = pd.read_sql_query("SELECT * FROM Stops", connection)
df_s

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17656\885771799.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_s = pd.read_sql_query("SELECT * FROM Stops", connection)

,id,startTime,endTime,downTime,orderStart,orderEnd,stopUpdatedTime,stopUpdatedBy,categoryName,subCategoryName,causeOne,causeTwo,causeThree,causeFour,causeFive,childDeviceName,deviceName,shiftName,shiftStartTime,shiftEndTime,deviceDataId,orderId,mainStopId,skuName,comment,reasonOne,reasonTwo,Status
0,3636,2024-02-01T15:00:09.000Z,2024-02-01T15:33:10.000Z,1981,02/01/2024 15:00:09,02/01/2024 22:59:43,,,Unplanned,,,,,,,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,348015,496,0,PET (400),,,,Completed
1,3637,2024-02-01T15:40:31.000Z,2024-02-01T15:46:10.000Z,339,02/01/2024 15:00:09,02/01/2024 22:59:43,,,Unplanned,,,,,,,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,348136,496,0,PET (400),,,,Completed
2,3638,2024-02-01T15:46:50.000Z,2024-02-01T16:07:11.000Z,1221,02/01/2024 15:00:09,02/01/2024 22:59:43,,,Unplanned,,,,,,,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,348155,496,0,PET (400),,,,Completed
3,3639,2024-02-01T16:07:51.000Z,2024-02-01T16:09:30.000Z,99,02/01/2024 15:00:09,02/01/2024 22:59:43,,,Unplanned,,,,,,,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,348218,496,0,PET (400),,,,Completed
4,3640,2024-02-01T16:10:30.000Z,2024-02-01T16:47:01.000Z,2191,02/01/2024 15:00:09,02/01/2024 22:59:43,,,Unplanned,,,,,,,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,348226,496,0,PET (400),,,,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2410,6046,2024-04-08T18:23:21.000Z,2024-04-08T18:26:41.000Z,200,04/08/2024 15:00:19,04/08/2024 22:59:43,,,Unplanned,,,,,,,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,555643,544,0,LDPE (400),,,,Completed
2411,6047,2024-04-08T18:43:21.000Z,2024-04-08T19:53:41.000Z,4220,04/08/2024 15:00:19,04/08/2024 22:59:43,,,Unplanned,,,,,,,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,555701,544,0,LDPE (400),,,,Completed
2412,6048,2024-04-08T20:53:02.000Z,2024-04-08T20:56:42.000Z,220,04/08/2024 15:00:19,04/08/2024 22:59:43,,,Unplanned,,,,,,,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,556088,544,0,LDPE (400),,,,Completed
2413,6049,2024-04-08T21:03:42.000Z,2024-04-08T21:23:02.000Z,1160,04/08/2024 15:00:19,04/08/2024 22:59:43,,,Unplanned,,,,,,,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,556120,544,0,LDPE (400),,,,Completed
2414,6050,2024-04-08T22:00:02.000Z,2024-04-08T22:13:23.000Z,801,04/08/2024 15:00:19,04/08/2024 22:59:43,,,Unplanned,,,,,,,MiraFlex 1,MiraFlex 1,B,15:00:00,23:00:00,556287,544,0,LDPE (400),,,,Completed